window.readingJson = [
	{
		title: ` Following some of the tips for green living helps save our planet. All of these involve just a f ew changes to our daily habits.
Just walk and limit the use of your car. One of the poster images of pollution is our vehicles. I t burns fuef. It is not as efficient as we hope it could be, and we use it even^ single day. To lessen t he eft^cts of the air pollution caused by our vehicles, we should limit their use. If we can walk to o ur destination then just let us go. (76)Not only do we lessen our carbon dioxide emissions, but we also get a good exercise out of it, •
Use a laptop instead of a computer desktop. Laptops are more energy efficient compared to th eir bigger counterparts. A laptop is generally 50 percent more efficient in using electricity. Aside fr om that there are other benefits of a laptop. It is portable so you can work an>^vhere you like and t hat you get powerful features without the large si^ of desktop units.
Turn off the faucet while you are brushing your teeth. It is always a better idea to use a glass when we are brushing our teeth and not to just let the faucet keep on running. Therefore ，
there is less water to waste while we are cleaning our pearly whites. Simply turn off the faucet wh en you are not using it.
Make good use of natural light. We have a great and natural lamp — the sun. and we should ! earn how to take full advantage of it during daytime, So instead of turning on our lights or lamps e ven if it is still not evening, we should pull up the drapes and let the natural light gome in from the windows.
These are just some of the best tips for green living, but of course there are still many of these tips if you just search for therrL (77)But you can do your own variation aay time just always priori tize how you can use less energy and produce even lesser trash and poHution. `,
		type: 2,
		arr: [
			'1. What\'s the best title for the passage?',
			'A. How to Save Our Planet',
			'B. How to Change Our Daily Habits',
			'C. Tips for Green Living Today',
			'D. Green Living and Serious Pollution',
			'答案：C',
			'2. Compared with a computer desktop, a laptop',
			'A. less energy efficient.',
			'B. faster at work.',
			'C. easy to repair. ^',
			'D. easy to cany.',
			'答案：D',
			'3. How many tips does the passage mention for green living today?',
			'A. Three ',
			'B. Four ',
			'C. Five ',
			'D. Six',
			'答案：B',
			'4. The imderlined word “prioritize” in the 1 肪t paragtaph can be replaced by the word',
			'A. decrease ',
			'B. consider ',
			'C. imagine ',
			'D. guess',
			'答案：B',
			'5. Which of the following is NOT true?',
			'A. A few changes to daily habits can help a lot.',
			'B. While washing teeth we should turn off the faucet.',
			'C. Vehicles bring pollution and we should try to avoid.',
			'D. In the daytime we should not pull up the drapes.',
			'答案：D',
		]
	},
	{
		title: ` One morning, Ann^ neighbor Tracy found a lost dog wandering around the local elementary school. She asked Ann if she could keep an eye on the dog. Ann said that she could watch it only for the day.
Tracy took photos oHhe dog and printed、off 400 FOUND fliers (传单），and put them in mailboxes. Meanwhile, Ann went to the dollar store and bought some pet supplies, warning her two sons not to fall in love with the dog. At the time, Ann^ son Thomas was 10 years old, and Jack, who was recovering from a heart operation, was 2! years old.
Four days later Ann was still looking after the dog, whom they had started to call Riley. When she arrived home from work, the dog threw itself against the screen door and barked madly at her. As soon as she opened the door, Riley dashed into the boys? room where Ann found Jack suffering from a heart attack. Riley ran over to Jack, but as soon as Ann bent over to help him the dog went silent.
“int hadn’t come to get me, the doctor said Jack would have died，” Arm reported to a local newspaper. (78)At this point, no one had called to claim the dog, so Ann decided to keep it.
The next morning Tracy got a call. A man named Peter recognized his lost dog and called the number on the flier. Tracy started cryfng, and told him, “That dog saved my friend’s son.”
Peter drove to Ann’s house to pick up his dog, and saw Thomas and Jack cjying in the window. After a few moments Peter said, 44Maybe Odie was supposed to find you, maybe you should keep it.” `,
		type: 2,
		arr: [
			'6. What did Tracy do after finding the dog?',
			'A. She looked for its owner',
			'B. She gave it to Ann as a gift.',
			'C. She sold it to the dollar store.',
			'D. She bought some food for it.',
			'答案：A',
			'7. How did the dog help save Jack?',
			'A. By breaking the door for Ann.',
			'B. By leading Ann to Jack’s room.',
			'C. By dragging Jack out of the room.',
			'D. By attending Jack when Ann was out.',
			'答案：B',
			'8. What was Ann’s attitude to the dog according to Paragraph 4?',
			'A. Sympathetic ',
			'B. Doubtful ',
			'C. Tolerant ',
			'D. Grateful',
			'答案：D',
			'9, For what purpose did Peter call Tracy?',
			'A. To help her friend’s son.',
			'B. To interview Tracy',
			'C. To take back his dog.',
			'D. To return the flier to her.',
			'答案：C',
			'10. What can we infer about the dog from the last p^agraph?',
			'A. It would be given to Odie.',
			'B. It would be kept by Ann? family.',
			'C. It would be returned to Peter,',
			'D. ft would be taken away by Tracy.',
			'答案：B',
		]
	},
	{
		title: ` It was one of those terribly hot days in Baltimore. Needless to say, it was too hot to do anything outside. But it was also scorching in our apartment This was 1962, and I would not live in a place with an air conditioner for another ten years： So my brother and I decided to leave the apartment to find someplace indoors. He suggested we could see a movie. It was a bnlliant plan.
(79)Movie theaters were one of the few places you could sit all day and—most important —sit in air conditioning. In those days, you could buy one ticket and sit through two movies. Then, the theater would show the same two movies again. If you wanted to, you could sit through them twice. Most people did not do that, but the manager at our theater. Mr. Bellow did not mind if you did.
That particular day5 my brother and I sat through both movies twice, tiying to escape the heat. We bought three bags of popcorn and three sodas each. Then, we sat and watched The Music Man followed by The Man Who Shot Liberty Valance. We?d already seen the second movie once before. It had been at the theater since January, because Mr, Bellow loved anything with John Wayne in it.
We left the theater around 8, just before the evening shows began. (8Q)But we returned the next day and saw the same two movies 故ain. twice more. And we did it the next day too. Finally, on the fourth day，the heat wave broke，
Still, to this day I can sing half the songs in The Music Man and recite half of John Wayne and Jimmy Stewards dialogue from The Man Who Shot Liberty Valance! Those memories are some of the few I have of the heat wave of 1962. They^re really memories of the screen, not memories of my life. `,
		type: 2,
		arr: [
			'11. In which year did the author first live in a place with an air conditioner?',
			'A. 1952 ',
			'B. 1962 ',
			'C. 1972 ',
			'D. 1982',
			'答案：C',
			'12. What does the underlined word in Paragi^)h 3 refer to?',
			'A. The heat',
			'B. The theater.',
			'C. The Music Man',
			'D. The Man Who Shot Liberty7 Valance',
			'答案：D',
			'13, What do we know about Mr. Bellow?',
			'A. He loved children very much.',
			'B. He was a fan of John Wayne.',
			'C. He sold air conditioners.',
			'D. He was a movie star*',
			'答案：B',
			'14. Why did the author and his/her brother see the same movies several times?',
			'A. The two movies were really wonderftil.',
			'B. They wanted to avoid the heat outside.',
			'C. The manager of the theater was friendly.',
			'D. They liked the popcorn and the soda at the theater.',
			'答案：B',
			'15. What can we learn from the last paragraph?',
			'A. The author turned out to be a great singer，',
			'B. The author enjoyed the heat wave of 1962.',
			'C. Theauthor’slifehasbeetiehangedbythetwomovies-',
			'D. I he author considers the experience at the theater unforgettable.',
			'答案：D',
		]
	},
	{
		title: ` Directions: In this part there are SO incomplete sentences. For each sentence there are four choices marked A, B, C and D. Choose (he ONE answer that best completes the sentence. Then blacken (he corresponding letter on the Answer Sheet. `,
		type: 2,
		arr: [
			'16. Happiness and success often come to those _____________are good at recognizing their own strengths.',
			'A. whom ',
			'B. who ',
			'C, what ',
			'D, which',
			'答案：B',
			'17. Experts believe______people can waste less food by shopping only when it is necessary.',
			'A. why ',
			'B. where ',
			'C. that ',
			'D. what',
			'答案：C',
			'18. Not once________to Michael that he could one day become a top student in his class.',
			'A. occurred it ',
			'B. it did occur ',
			'C. it occmred ',
			'D. did it occur',
			'答案：D',
			'19. _______which university to attend, the girl asked her teacher for advice.',
			'A. Not knowing ',
			'B. Knowing not ',
			'C. Not known ',
			'D. Known not',
			'答案：A',
			'20. The Smiths are praised________the way they bring up their children.',
			'A. from ',
			'B. by ',
			'C. at ',
			'D. for ,"',
			'答案：D',


			'21. Young people may risk__________deaf if they are exposed to very loud music every day.',
			'A. to go ',
			'B. to have gone ',
			'C. going ',
			'D. having gone',
			'答案：C',
			'22. Poetry written from the_______of the urban youth tends to reveal their anxiety over a lack of sense of belonging.',
			'A. perspective ',
			'B. priority ',
			'C. participation ',
			'D. privilege',
			'答案：A',
			'23. To make members of a team perform better, the trainer first of all has to know their__________andweaknesses.',
			'A. strengths ',
			'B. benefits ',
			'C. techniques ',
			'D. values',
			'答案：A',
			'24.She_________the carpet with some very nice curtains in colour.',
			'A. connected ',
			'B. fitted ',
			'C. equipped ',
			'D. matched',
			'答案：D',
			'25.—This is your order, a hamburger and an apple pie.___________ ?',
			'A. Anything else ',
			'B. Is that OK ',
			'C. For here or to go ',
			'D. Something to drink ',
			'答案：C',


			'26.Only by increasing the number of doctors by 50 percent___________ properly in this hospital.',
			'A. can be the patients ',
			'B. can the patients be treated ',
			'C. the patients can be treated ',
			'D. treated can be the patients',
			'答案：B',
			'27.The students are looking forward to having an opportunity _________________ society for real-life experience.',
			'A. explore ',
			'B. to explore ',
			'C. exploring ',
			'D, explored',
			'答案：B',
			'28.1 should not have laughed if I_______you were serious.',
			'A. thought ',
			'B. would think ',
			'C. had thought ',
			'D. have thought',
			'答案：C',
			'29.She says that she5li have to close the shop____________business improves,',
			'A. if ',
			'B. unless ',
			'C. after ',
			'D. when',
			'答案：B',
			'30.The airport —______next year will he!p promote tourism in this area,',
			'A. being completed ',
			'B, to be completed ',
			'C. completed ',
			'D. having been completed ',
			'答案：B',


			'31 .—The town is So beautiful! I just love it. —Me too. The character of the town is well ______',
			'A. qualified ',
			'B. preserved ',
			'C decorated ',
			'D. simplified',
			'答案：B',
			'32.1 didn5t think Fd like the movie, but actually it________pretty good,',
			'A. has been ',
			'B. was ',
			'C, had been ',
			'D. would be',
			'答案：B',
			'33 Animals are obviously______lower form of life than__________man.',
			'A. a； / ',
			'B. the； the ',
			'C. a; the ',
			'D. /； /',
			'答案：A',
			'34.Generally, students7 inner motivation with high expectations from others ______ essential to their development',
			'A. is ',
			'B. are ',
			'C. was ',
			'D, were',
			'答案：A',
			'35.If he had spent more time practicing speaking English before, he______ able to speak; itmuch better now.',
			'A. will be ',
			'B. would be ',
			'C. has been ',
			'D. would have been',
			'答案：B',


			'36. —Thank you for the flowers.—_____. I thought they might cheer you up,',
			'A. Thafs right ',
			'B. All right ',
			'C. Fm all right ',
			'D. If s all right',
			'答案：D',
			'37. Whenever I made mistakes* the teacher pointed them out with______',
			'A. curiosity ',
			'B. satisfaction ',
			'C. envy ',
			'D, patience',
			'答案：D',
			'38.David is ______ animal fiir, so he won?t visit anyone who has cats or dogs in the house.',
			'A. curious about ',
			'B. allergic to ',
			'C. satisfied with ',
			'D, food of',
			'答案：B',
			'39. What a terrible experience!______, you\'re safe now—thafs the main thing.',
			'A. Anyway ',
			'B. Besides ',
			'C. Otherwise ',
			'D. Therefore',
			'答案：A',
			'40. Mother always compiains that children_______ their shoes very quickly.',
			'A. find out ',
			'B. washout ',
			'C. wear out ',
			'D, set out',
			'答案：C',


			'41. _______one of you breaks the window will have to pay for it.',
			'A. Whoever ',
			'B. Whatever ',
			'C. Whichever ',
			'D» Wherever',
			'答案：C',
			'42. Michelle found a job as a high school teacher which_________ spending quite a lot of time withstudents.',
			'A. enjoys ',
			'B. involves ',
			'C. practices ',
			'D. suggests',
			'答案：B',
			'43. Volunteering gives you a chance________ lives, including your own.',
			'A. change ',
			'B. changing ',
			'C. changed ',
			'D, to change',
			'答案：D',
			'44,Shakespeare,s play Hamlet_________ into at least ten different films over the past years.',
			'A. had been made ',
			'B. was made ',
			'C, has been made ',
			'D. would be made',
			'答案：C',
			'45.Many countries are now setting up national parks___________animals and plants can be protected.',
			'A. when ',
			'B. which ',
			'C. whose ',
			'D, where',
			'答案：D',
		]
	},
	{
		title: ` Part III Identification (10%)Directions: Each of the following sentences has four underlined parts marked At B, C and D. Identify the one that is not correct Then blacken the corresponding letter on the Answer Sheet. `,
		type: 2,
		arr: [
			'46. <em class="col-red">(Read)</em> this story, <em class="col-red">(but)</em> you will realize that not <em class="col-red">(everything)</em> can be bought <em class="col-red">(with)</em> money,',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：B',
			'47. When I was <em class="col-red">(little)</em>, my mother <em class="col-red">(used to sit)</em> <em class="col-red">(by)</em> my bed, <em class="col-red">(to tell)</em> me stories till I fell asleep.',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：D',
			'48. The traffic <em class="col-red">(on)</em> the main streets has a <em class="col-red">(longer)</em> green signal <em class="col-red">(than)</em> <em class="col-red">(it)</em> on the small ones.',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：D',
			'49. <em class="col-red">(That)</em> <em class="col-red">(makes)</em> the book <em class="col-red">(so)</em> extraordinary is the <em class="col-red">(creative)</em> imagination of the writer.',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：A',
			'50.<em class="col-red">(Seeing)</em> Michael <em class="col-red">(so)</em> sad, I wish I <em class="col-red">(haven’t)</em> told him the <em class="col-red">(truth.)</em>',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：C',


			'51.1 will give you my <em class="col-red">(friend’s)</em> home adress.<em class="col-red">(which)</em> I can be <em class="col-red">(reached)</em> <em class="col-red">(most)</em> evenings.',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：B',
			'52.<em class="col-red">(Let’s)</em> go and <em class="col-red">(watch)</em> that new movie <em class="col-red">(at eight)</em> tomorrow night, <em class="col-red">(won’t we)</em>?',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：D',
			'53.<em class="col-red">(Studying)</em> abroad <em class="col-red">(gives)</em> you a chance <em class="col-red">(experiencing)</em> different <em class="col-red">(cultures)</em>,',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：C',
			'54. Two <em class="col-red">(woman)</em> teachers and four <em class="col-red">(girl)</em> students <em class="col-red">(were)</em> praised <em class="col-red">(at the meeting)</em> yesterday.',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：A',
			'55. How <em class="col-red">(could)</em> you make <em class="col-red">(such)</em> a little girl <em class="col-red">(to help)</em> you <em class="col-red">(carry)</em> the big box?',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：C',
		]
	},
	{
		title: ` Dale Carnegie rose from the unknown of a Missouri farm to international fame because he
found a way to fill a universal human need.
It was a need that he first <em class="col-red">____56____</em> back in 1906 when young Dale was a junior at State Teachers College in Warrensburg. To get an <em class="col-red">____57____</em> , he was struggling against many difficulties.
His family was poor. His Dad couldn’t afford the <em class="col-red">____58____</em> at college, so Dale had to ride horseback 12 miles to attend classes. Study had to be done <em class="col-red">____59____</em> his farm-work routines. He withdrew from many school activities <em class="col-red">____60____</em> he didn’t have the `,
		type: 2,
		arr: [
			'56. ',
			'A. admitted',
			'B. filled',
			'C. supplied',
			'D. recognized',
			'答案：D',
			'57. ',
			'A. assignment',
			'B. education',
			'C. advantage',
			'D. instruction',
			'答案：B',
			'58. ',
			'A. training',
			'B. board',
			'C. teaching',
			'D. equipment',
			'答案：B',
			'59. ',
			'A. between',
			'B. during',
			'C. over',
			'D. through',
			'答案：A',
			'60. ',
			'A. while',
			'B. when',
			'C. because',
			'D. though',
			'答案：C'
		]
	},
	{
		title: ` time or the <em class="col-red">____61____</em> , He had only one good suit. He
tried <em class="col-red">____62____</em> the football team, but the coach turned him down for being too <em class="col-red">____63____</em> ，During this
period Dale was slowly <em class="col-red">____64____</em> an inferiority complex (自卑感}，which his mother knew coiUd <em class="col-red">____65____</em> him from achieving his real potential. `,
		type: 2,
		arr: [
			'61. ',
			'A. permits',
			'B. interest',
			'C. talent',
			'D. clothes',
			'答案：D',
			'62. ',
			'A. on',
			'B. for',
			'C. in',
			'D. with',
			'答案：B',
			'63. ',
			'A. light',
			'B. flexible',
			'C, optimistic',
			'D. outgoing',
			'答案：A',
			'64. ',
			'A. gaining',
			'B. achieving',
			'C. developing',
			'D‘ obtaining',
			'答案：C',
			'65. ',
			'A. prevent',
			'B. protect',
			'C.save',
			'D. free',
			'答案：A',
		]
	},
	{
		title: ` She <em class="col-red">____66____</em> that Dale join the debating team, believing that <em class="col-red">____67____</em> in speaking could give him the confidence and recognition that he needed.
Dale took his mother^ advice, tried desperately and after several attempts <em class="col-red">____68____</em> made it, 
This proved to be a <em class="col-red">____69____</em> point in his life. Speaking before groups did help him gain the <em class="col-red">____70____</em> he needed. `,
		type: 2,
		arr: [
			'66. ',
			'A. suggested',
			'B. demanded',
			'C. required',
			'D. insisted',
			'答案：A',
			'67. ',
			'A. presence',
			'B. practice',
			'C. patience',
			'D. potential',
			'答案：B',
			'68. ',
			'A. hopefully',
			'B. certainly',
			'C. finally',
			'D. naturally',
			'答案：C',
			'69. ',
			'A. key',
			'B. breaking',
			'C. basic',
			'D. turning',
			'答案：D',
			'70. ',
			'A. progress',
			'B. experience',
			'C. competence',
			'D. confidence',
			'答案：D',
		]
	},
	{
		title: ` By the time Dale was a senior, he had won every top honor in <em class="col-red">____71____</em> . Now other students
were coming to him for coaching and they, <em class="col-red">____72____</em>, were winning contests.
Out of this early struggle to <em class="col-red">____73____</em> his feelings of inferiority, Dale came to understand that the ability to <em class="col-red">____74____</em> an idea to an audience builds a person^ confidence. And, <em class="col-red">____75____</em> it, Dale knew he could do anything he wanted to do—and so could others. `,
		type: 2,
		arr: [
			'71. ',
			'A. horse-riding ',
			'B, football',
			'C. speech',
			'D. farming',
			'答案：C',
			'72. ',
			'A. in return',
			'B. in brief',
			'C. in turn',
			'D, in fact',
			'答案：C',
			'73. ',
			'A. convey',
			'B. overcome',
			'C. understand',
			'D. build',
			'答案：B',
			'74. ',
			'A. express',
			'B. stress',
			'C. contribute',
			'D. repeat',
			'答案：A',
			'75. ',
			'A. besides',
			'B. beyond',
			'C. like',
			'D. with',
			'答案：D'
		]
	}
]