window.readingJson = [
	{
		title: `Elizabeth Freeman was bom about 1742 to African American parents who were slaves. At the age of six months she was acquired, along with her sister, by John Ashley, a wealthy Massachusetts slaveholders. She became known as “Mumbet” or “Mum Belt.”
For nearly 30 years Mumbet served the Ashley family. One day, Ashley^ wife tried to strike Mumbefs sister with a spade. Mumbet protected her sister and took the blow instead. Furious, she left the house and refused to come back. When the Ashleys tried to make her return, Mumbet consulted a lawyer, Theodore Sedgewick. With his help, Mumbet sued(JflW) for her freedom.
While serving the Ashleys, Mumbet had listened to many discussions of the new Massachusetts constitution. If the constitution said that all people were free and equal, then she thought it should apply to her. Eventually, Mumbet won her freedom — the first slave in Massachusetts to do so under the new constitution.
(76)Strangelv enough, after the trial, the Ashleys asked Mumbet to come back and work for them as a paid employee. She dec羞ined and instead went to work f〇f Segdewick. Mumbet died in 1829, but her iegacy lived on in her many descendants(后裔).One of her great-grandchildren was W.E.B. Du Bois，one of the founder of the N A AC P，and an important writer and spokesperson for African American civil rights.
Mumbefs tombstone still stands in the Massachusetts cemetery where she was buried. It reads, in part: 4<She was born a slave and remained a slave and remained a slave for nearly thirty years. She could neither read nor write, yet in her own sphere she had no superior or equal.，’`,
		type: 2,
		arr: [
			'1. What do we know about Mumbet according to Paragraph 1?',
			'A. She was bom a slave',
			'B. She was a slaveholder',
			'C. She had a famous sister',
			'D. She was born into a rich family',
			'答案：A',
			'2. Why did Mumbet run away from the Ashleys?',
			'A. She found an employer.',
			'B. She wanted to be a lawyer.',
			'C. She was hit and got angry,',
			'D. She had to take care of her sister.',
			'答案：C',
			'3. What did Mumbet learn from discussions about the new consititution?',
			'A. She should always obey her owners1 orders.',
			'B. She should be as free and equal as whites.',
			'C. How to be a good servant.',
			'D. How to apply for a job.',
			'答案：B',
			'4. What did Mumbet do after the trial?',
			'A. She chose to work for a lawyer.',
			'B. She found the NAACP.',
			'C. She continued to serve the Ashleys.',
			'D. She went to live with her grandchildren.',
			'答案：A',
			'5. What is the test mainly about?',
			'A. A story of a famous writer and spokesperson.',
			'B. The friendship between a lawyer and a slave.',
			'C. The life of a brave African American woman,',
			'D. A trial that shocked the whole world.',
			'答案：C',
		]
	},
	{
		title: `How fit are your teeth? Are you lazy about brushing them? Never fear: An inventor is on the case. (77)An electric toothbrush senses how long-atid how well you brush, and it lets you track your performance on your phone.
The Koiibree toothbrush was exhibited at the International Consumer Electronics Show in Las Vegas this week. It senses how it is moved and can send the information to an Android phone or iPhone via a Bluetooth wireless connection.
The toothbrush will be able to teach you to brush right (don^ forget the insides of the teeth!) and make sure you’re brushing bng enough. kind of like having a dentist actually watch your brushing on a day-to-day basis/1 says Thomas Serval, the French inventor
The toothbrush wil! also be abte to talk to other applications on your phorve，so devdopers could, for instance, create a game controlled by your toothbrush. You could score points for beating monsters among your teeth. 4iWe try to make it smart but also fun,^ Several says.
Serval says he was inspired by his experience as a father, lie would come home from work and ask his kids if they had brushed their teeth. They said but Serval would find their
4 ，
toothbrush heads dry. He decided he needed a brush that really told him how well his children brushed.
(78)The company says the Kolibree will go on sale this summer, for $99 to $199, developing on features. The U.S. is the first target market.
Serval says that ooe day, if II be possible to replace the brush on the handle with a brushing unit that also has a camera. The camera can even examine holes in your teeth while you brush.`,
		type: 2,
		arr: [
			'6. Which is one of the feature of the Kolibree toothbrush?',
			'A. It can sense how users brush their teeth.',
			'B. It can track users\' school performance.',
			'C. It can detect users, fear of seeing a dentist',
			'D. It can help users find their phones,',
			'答案：A',
			'7. What can we learn from Servafs words in Paragraph 3?',
			'A. You will find it enjoyable to see a dentist,',
			'B. You should see your dentist on a day4o -day basis.',
			'C. You can brush with the Kolibree as if guided by a dentist.',
			'D. You^ like a dentist to watch you brush your teeth every day.',
			'答案：C',
			'8. Which of the following might make the Kolibree toothbrush fun?',
			'A. It can be used to update mobile phones.',
			'B. It can be used to play mobile phone games.',
			'C. It can send messages to other users.',
			'D. It can talk to its developers.',
			'答案：B',
			'9. What is Paragraph 5 mainly about?',
			'A. How Serval found out his kids lied to him.',
			'B. Why Serval thought brushing teeth was necessary.',
			'C. How Serval taught his kids to brush their teeth.',
			'D. What inspired Serval to invent the toothbrush.',
			'答案：D',
			'10. What can we infer about Serval^ children?',
			'A. They were unwilling to brush their teeth.',
			'B. They often failed to clean their toothbrushes.',
			'C. They preferred to use a toothbrush with a dry head.',
			'D. They liked brushing their teeth after Serval came home.',
			'答案：A',
		]
	},
	{
		title: `Samuel Osmond is a 19-year-old law student from Cornwall, England. He never studied the piano. However, he can play very difficult musical pieces by musicians such as Chopin and Beethoven just a few minutes after he hears them. He learns a piece of music by listening to it in parts. Then he thinks about the notes in his head. Two years ago, he played his first piece Moonlight Sonata (奏鸣曲）by Beethoven. He surprised everyone around him.
(79)Amazed that he remembered this long and difficult piece of music and ptaved it perfectly, his teachers say Samuel is unbelievable. They say his ability is very rare，but Samuel doesn’t even realize that what he can do is special. Samuel wanted to become a lawyer as it was the wish of his parents, but music teachers told him he should study music instead. Now, he^ studies law and music.
Samuel can’t understand why everyone is so surprised “I grew up with music。My mother played the piano and my father played the guitar. About two years ago, I suddenly decided to start playing the piano, without being able to read music and without having any lessons. It comes easily to me I hear the notes and can bear them in mind---each and every note，’’ says Samuel.
Recently, Samuel performed a piece during a special event at his college. The piece had more than a thousand notes. The audience was impressed by his amazing performance. He is now learning a piece that is so difficult that many professional pianists canH play it Samuel says confidently，” It’s ail about super memory---1 guess l have that gift.”
However, SamueFs ability to remember things doesn't stop with music. (80)His family says that even when he was a young boy, Samuel heard someone read a story, and then he could retcil the story word for word.
Samuel is still only a teenager. He doesn^ know what he wants to do in the future. For now, he is just happy to play beautiful music and continue his studies.`,
		type: 2,
		arr: [
			'11. What is special about Samuel Osmond?',
			'A. He has a gift for writing music.',
			'B. He can write down the note he hears.',
			'C. He is a top student at the law school.',
			'D. He can play the musical piece he hears.',
			'答案：D',
			'12. What can we learn from Paragraph 2?',
			'A. Samuel chose law against the wish of his parents，',
			'B. Samuel planned to be a lawyer rather than a musician.',
			'C. Samuel thinks of himself as a man of great musical ability.',
			'D. Samuel studies law and music on the advice of his teachers.',
			'答案：B',
			'13. Everyone around Samuel was surprised because he',
			'A . received a good early education in music.,',
			'B. played the guitar and the piano perfectly.',
			'C. could play the piano without reading music. .',
			'D. could play the guitar better than his father.',
			'答案：C',
			'14. What can we infer about Samuel in Paragraph 4?',
			'A. He became famous during a special event at his college.',
			'B. He is proud of his ability to remember things accurately.',
			'C. He plays the piano better than many professional pianists.',
			'D. He impressed the audience by playing all the musical pieces.',
			'答案：B',
			'15. Which of the following is the best title of the passage?',
			'A. The Qualities of a Musician.',
			'B. The Story of a Musical Talent. .-',
			'C. The Importance of Early Education.',
			'D. The Relationship between Memory and Music.',
			'答案：B',
		]
	},
	{
		title: `Directions: In this part there are 30 incomplete sentences. For each sentence there are four choices marked A, B, C and D. Choose the ONE answer that best completes the sentence. Then blacken the corresponding letter on the Answer Sheet. 16 17 18 * 20`,
		type: 2,
		arr: [
			'16. 一What about your self-drive trip yesterday? —Tiring! The road is being widened. and we________a round ride.',
			'A. had ',
			'B. have ',
			'C. would have ',
			'D. have had',
			'答案：A',
			'17. My mom suggests that we________eat out for a change this weekend.',
			'A. should ',
			'B. might ',
			'C. could ',
			'D. would',
			'答案：A',
			'18. There are a small number of people involved. possibly_________twenty.',
			'A. as few as ',
			'B. as little as ',
			'C. as many as ',
			'D. as much as',
			'答案：A',
			'19.If parents have children help with housework. the children will feel needed.__________.they will 1earn to take care of themselves.',
			'A. On the contrary ',
			'B. In a word ',
			'C. That is to say ',
			'D. What’s more',
			'答案：D',
			'20._______is often the case with children. Amy was better by the time the doctor arrived.',
			'A. It ',
			'B. That ',
			'C. What ',
			'D.As',
			'答案：D',


			'21._______ the course very difficult. she decided to move to a lower level.',
			'A. Find ',
			'B. Finding ',
			'C. To find ',
			'D. Found',
			'答案：B',
			'22.It’s so nice to hear from her again.________ . we last met more than thirty years ago.',
			'A. What’s more ',
			'B.Thaf s to say ',
			'C. In other words ',
			'D. Believe it or not',
			'答案：D',
			'23. —Thanks a lot for your bookJ found it very interesting.______ .I’m glad you enjoyed it.',
			'A. All the best ',
			'B. It is nothing ',
			'C. No thanks ',
			'D.Very well',
			'答案：B',
			'24. “Never for a second.” the boy says. _____that my father would come to my rescue.”',
			'A. I doubted ',
			'B. do I doubt ',
			'C. I have doubted ',
			'D. did I doubt',
			'答案：D',
			'25. He didn’t fed like ______that day so he stayed indoors reading.',
			'A .working ',
			'B. works ',
			'C. to work ',
			'D.worked',
			'答案：A',


			'26. Among the crises that face humans__________the lack of natural resources.',
			'A. is ',
			'B. are ',
			'C. is there ',
			'D. are there',
			'答案：A',
			'27.-Mrs. Smith finds it hard to clear up the mess. as her children are always___________whenever shetries to.',
			'A.in the way ',
			'B. on watch ',
			'C. in sight ',
			'D. on the line',
			'答案：A',
			'28.__Those poor and needy teenagers were excited to find a shop at the comer where they could buy ______priced bikes.',
			'A. competitively ',
			'B. recently ',
			'C. reasonably ',
			'D. affordably',
			'答案：D',
			'29. Carbon dioxide. which makes a________between us and the sun. prevents heat from getting out of the atmosphere easily. so the earth is becoming warmer.',
			'A. difference ',
			'B. comparison ',
			'C. connection ',
			'D. barrier',
			'答案：D',
			'30.1 had hoped to take a holiday this year but I wasn\'t able to____________.',
			'A. get away ',
			'B. drop in ',
			'C. check oat ',
			'D. hold on',
			'答案：A',


			'31. Do not let any failures discourage you. for you can never tell_____________close you may be to victory. .',
			'A. how ',
			'B. that ',
			'C.which ',
			'D. where',
			'答案：A',
			'32. While intelligent people can often_______the complex. a fool is more likely to complicate the simple.',
			'A. sacrifice ',
			'B. substitute ',
			'C. simplify ',
			'D. survive',
			'答案：C',
			'33. People complain that decisions to approve or deny a permit are often_________rather than based on fixed criteria.',
			'A. appropriate ',
			'B. conscious ',
			'C. arbitrary ',
			'D. controversial',
			'答案：C',
			'34. Butterf!ies_______a sweet liquid produced by flowers. which bees and other insects collect.',
			'A. carry on ',
			'B. feed on ',
			'C. put on ',
			'D. focus on',
			'答案：B',
			'35. He didnJt selfishly keep for himself the money inherited from his uncle. Instead. he made a_______contribution to help the community.',
			'A. commercial ',
			'B. generous ',
			'C. comparable ',
			'D. profitable',
			'答案：B',


			'36. Poetry written from the _____ of the urban youth tends to reveal their anxiety over a lack of sense of belonging.',
			'A. perspective ',
			'B. priority ',
			'C. participation ',
			'D. privilege',
			'答案：A',
			'37.1 have an appointment ________ Dr. Smith. but l need to change it.',
			'A. to ',
			'B. off ',
			'C. with ',
			'D. from',
			'答案：C',
			'38. Nowadays people are more eoneemed about the environment ______ they live.',
			'A. what ',
			'B. which ',
			'C. when ',
			'D. where',
			'答案：D',
			'39. --- You needn\'t take an umbrella. It isn\'t going to rain. —Well. I don’t know. It ________do',
			'A. might ',
			'B. need ',
			'C. would ',
			'D. should',
			'答案：A',
			'40. ___we have enough evidence. we can\'t win the case.',
			'A. Once ',
			'B. As long as ',
			'C. Unless ',
			'D. Since',
			'答案：C',


			'41 How did your interview with the manager go? ---________He seemed interested in my experience. but he didn.t ask for references.',
			'A. Perfect! ',
			'B. I\'m not sure. ',
			'C. That’s right. ',
			'D. Couldn’t be better.',
			'答案：B',
			'42. Fve lived in New York and Chicago. but don’t like_______of them very much.',
			'A.either ',
			'B. any ',
			'C. each ',
			'D.another',
			'答案：A',
			'43. You hair wants_______.You^ better have it done tomorrow.',
			'A.cut ',
			'B.to cut ',
			'C.catting ',
			'D.being cut',
			'答案：C',
			'44 If we_______ a table earlier. we couldn^t be standing here in a queue.',
			'A. have booked ',
			'B. booked ',
			'C. book ',
			'D. had booked',
			'答案：D',
			'45.He may win the competition._______________he b Hkely to get into the natiofial team.',
			'A. in which case ',
			'B. in that case ',
			'C. in what case ',
			'D. in whose case',
			'答案：A',
		]
	},
	{
		title: `Directions; Each of the following sentences has four underlined parts marked Af Bf C and D. Identify the one that is not correct Then blacken the corresponding letter on the Answer Sheet`,
		type: 2,
		arr: [
			'46. Those who smoke <em class="col-red">(heavily)</em> should remind <em class="col-red">(them)</em> <em class="col-red">(of)</em> health, the bad smell and the feelings of <em class="col-red">(other)</em> people.',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：B',
			'47. The engine <em class="col-red">(just)</em> won\'t <em class="col-red">(start)</em>. Something seems <em class="col-red">(to go)</em> wrong <em class="col-red">(with)</em> it ',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：C',
			'48.1 <em class="col-red">(was)</em> glad <em class="col-red">(to meet)</em> Jenny again, <em class="col-red">(so)</em> I didn?t want to spend all day <em class="col-red">(with)</em> her. ',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：C',
			'49, <em class="col-red">(Easter)</em> is <em class="col-red">(a)</em> happy holiday <em class="col-red">(where)</em> children enjoy <em class="col-red">(hunting for)</em> Easter eggs,',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：C',
			'50. The film star <em class="col-red">(wears)</em> <em class="col-red">(sundasses)</em>. <em class="col-red">(Therefore)</em>, he can go shopping without <em class="col-red">(recognized)</em>.',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：D',


			'51, You <em class="col-red">(have)</em> <em class="col-red">(heard from)</em> him <em class="col-red">(since)</em> last year, <em class="col-red">(have you)</em>?',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：D',
			'52,<em class="col-red">(Working)</em> hard <em class="col-red">(for)</em> many years, Li Na <em class="col-red">(harvested)</em> the rewards of her <em class="col-red">(efforts)</em>,',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：A',
			'53. There <em class="col-red">(will be)</em> more than <em class="col-red">(three hundreds)</em> students <em class="col-red">(taking)</em> part in the <em class="col-red">(sports meet)</em>.',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：B',
			'54. You <em class="col-red">(can see)</em> the whole city <em class="col-red">(for)</em> miles <em class="col-red">(from here)</em> <em class="col-red">(in)</em> a dear day,',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：D',
			'55.It’s good <em class="col-red">(to know)</em> <em class="col-red">(what)</em> the dogs will be well cared <em class="col-red">(for)</em> while we are <em class="col-red">(away)</em>',
			'AAAAA',
			'BBBBB',
			'CCCCC',
			'DDDDD',
			'答案：B',
		]
	},
	{
		title: `Mum, can I invite my classmate Brett over to stay tomorrow night, please? Ifs Friday, and we don’t have any <em class="col-red">____56____</em> .Can I, please?^ Mum was sitting at the kitchen table. Dad was <em class="col-red">____57____</em> next to her, resting his head on his arms. Mum could <em class="col-red">____58____</em> that James wanted so badly to have his friend over.
“I’m so sorry，James,” she said.
“I’m never allowed to have friends come to the house? Why, Mum?” James asked sad!y，almost in <em class="col-red">____59____</em> .
“[know it’s <em class="col-red">____60____</em> for you，” Mum said softly. “But I’m just worried other people might think we’re a little", strange. And then they would make fiin of you,”`,
		type: 2,
		arr: [
			'56. ',
			'A. chance ',
			'B.message ',
			'C. homework ',
			'D.difficulty',
			'答案：C',
			'57. ',
			'A. a sleep ',
			'B.reading ',
			'C. alone ',
			'D.standing',
			'答案：A',
			'58. ',
			'A. explain ',
			'B.see ',
			'C. agree ',
			'D. doubt',
			'答案：B',
			'59.',
			'A. terror',
			'B. tears',
			'C. surprise',
			'D. silence',
			'答案：B',
			'60.',
			'A. fair',
			'B. easy',
			'C. good',
			'D. hard',
			'答案：D',
		]
	},
	{
		title: `“No, they wouldn’t, Mum，” James protested. “We’re not <em class="col-red">____61____</em> at all. We’re just ordinary people.”
Mum sighed heavily. u To tell you the truth, James, my neck has been so painful that ifs given me a heavy <em class="col-red">____62____</em> • And your poor father -he doesn’t fed <em class="col-red">____63____</em> . He really needs a rest.”
“I can help，Mum!” James said. ‘‘ <em class="col-red">____64____</em> I can make you and Dad feel better, can Brett come over?
Please?” ，
“Well began.
‘‘Great! Thanks，Mum!” James almost shouted. ‘‘ Just sit there, don’t move.” He rushed over to the kitchen drawer and <em class="col-red">____65____</em> what he needed — two zxxk.com spanners. “ Hang on，Mum，” he said. `,
		type: 2,
		arr: [
			'61.',
			'A. strange',
			'B. normal',
			'C. popular',
			'D. anxious',
			'答案：A',
			'62.',
			'A. headache',
			'B. loss',
			'C.task',
			'D. day',
			'答案：A',
			'63.',
			'A. ill',
			'B. funny',
			'C. sorry',
			'D. well',
			'答案：D',
			'64.',
			'A. As',
			'B. If',
			'C. Since',
			'D. Before',
			'答案：B',
			'65.',
			'A. kept',
			'B. controlled',
			'C. found',
			'D. returned',
			'答案：C',
		]
	},
	{
		title: `“ This won’t take a second.” After some <em class="col-red">____66____</em> , James was finished. With a smile of <em class="col-red">____67____</em>
on his face he said，“ There! How does that feel?” ‘‘ Oh，James，’’ Mum said. “ That’s a much better! How did you do it?”
“Easy,” James said <em class="col-red">____68____</em> Dad had tightened your neck bolts (螺栓）too much! I just <em class="col-red">____69____</em> them slightly ! I learned that in robotic science at school.^
“What about you father? Can you <em class="col-red">____70____</em> him?” asked Mum.`,
		type: 2,
		arr: [
			'66.',
			'A. requests',
			'B. thoughts',
			'C. repairs',
			'D. instructions',
			'答案：C',
			'67.',
			'A. sympathy',
			'B. satisfaction',
			'C bitterness',
			'D. politeness',
			'答案：B',
			'68.',
			'A. embarrassedly',
			'B. gratefully',
			'C. impatiently',
			'D. proudly',
			'答案：D',
			'69.',
			'A. adjusted',
			'B. collected',
			'C. produced',
			'D. covered',
			'答案：A',
			'70.',
			'A. greet',
			'B. accompany',
			'C. help',
			'D. ask',
			'答案：C',
		]
	},
	{
		title: `“I，il try,” James replied. He <em class="col-red">____71____</em> up Dad’s hair at the back; of his neck, and plugged the electric wire into Dad’s head. Then he turned the <em class="col-red">____72____</em> on. Dad opened his eyes and <em class="col-red">____73____</em> immediately .
“ He just let his <em class="col-red">____74____</em> run too low，that’s a",” James said，“Shall f tell Brett to come over straight after school tomorrow?”
“I guess so,” replied Mum。“ Your friends will just have to <em class="col-red">____75____</em> that we are a very unusual family. Thanks，son !’’`,
		type: 2,
		arr: [
			'71.',
			'A. lifted',
			'B. caught',
			'C. gave',
			'D. filled',
			'答案：A',
			'72.',
			'A. television',
			'B. power',
			'C. light',
			'D. gas',
			'答案：B',
			'73.',
			'A. grew up',
			'B. lay down',
			'C. broke down',
			'D. sat up',
			'答案：D',
			'74.',
			'A. food',
			'B. temperature',
			'C. battery',
			'D. blood',
			'答案：C',
			'75.',
			'A. prove',
			'B. expect',
			'C. suspect',
			'D. accept',
			'答案：D',
		]
	}
]