window.readingJson = [

    {
        title: `(76)The National Trust in Britain plays an increasingly important part in the preservation for publ ic enjoyment of the best that is le ft unspoiled of the British countryside. A lthough the Trusthas received practical and moral support from the Government, it is not a rich Government department, ft is a voluntary association of people who care for the unspoiled countryside and historic buildings of Britain. It is a charity which depends for its existence on voluntary support from members of the public'. Its primary duty is to protect places of great natural beauty and places of historical interest .
The attention of the public was first drawn to the dangers threatening the great old houses and castles of Britain by the death of Lord Lothian, who left his great seventeenth-century house to the Trust together with the 4500~acre park and estate surrounding it.This gift attracted wide publicityand started the Trust's '"Country House Scheme,1. Under this scheme, with the help of the Government and the general public, the Trust has been able to save and make accessible to the public about one hundred and fifty of these old houses2. Last year about one and three quarters of amillion people paid to visit these historic houses, usually at a very small charge.
In addition to country houses and open spaces the Trust now owns some examples of
/
ancientwind and water mills3, nature reserves4, five hundred and forty farms and nearly two thousand fivehundred cottages or small village houses, as well as some complete tillages. In these villages noone is allowed to buildt develop 'or disturb the old village environment in any way and all the houses are maintained in their original sixteenth-century style. Over four hundred thousand acres of coastline, woodland, and hill country are protected by the Trust and no development or disturbances of any kind are permitted. The public has free access to these areas and is only asked to respect thepeace, beauty and wildlife.
So it is that over the past eighty years the Trust has become a big and important organizationand an essential and respected part of national life, preserving all that is of great natural beauty arid of historical significance not only for future generations of Britons but also for the millions of tourists who each year invade Britain in search of a great historic and cultural heritage.`,
        type: 2,
        arr: [
            '1. The National Trust is a',
            'A. government agency depending on voluntary services.',
            'B. non-profit organization depending on voluntary services.',
            'C. government department but is not rich.',
            'D. private organization supported by the government.',
            '答案：B',
            '2. The National Trust is dedicated to',
            'A. preserving the best public enjoyment.',
            'B. providing the public with free access to historic buildings.',
            'C. offering better services to visitors home and abroad.',
            'D. protecting the unspoiled countryside and historic buildings.',
            '答案：D',
            '3. We can infer from Paragraph 2 that Lord Lothian',
            'A. donated all his money to the Trust.',
            'B. started the “Country House Scheme”.',
            'C. saved many old country houses in Britain.',
            'D. was influenced in his life.',
            '答案：D',
            '4. AH the following can be inferred from the passage EXCEPT',
            'A. The Trust is more interested in protecting the 16th century houses.',
            'B. Many people came to visit the historic houses saved by the Trust.',
            'C. Visitors can get free access to some places owned by the Trust',
            'D. The Trust has a story which is longer than 80 years.',
            '答案：C',
            '5. The word “irvvade” in Paragraph 4 is closet in meaning to',
            'A. Come in without permission.',
            'B. Enter with invitation.',
            'C. Visit in large numbers.',
            'D. Appear all of a sudden.',
            '答案：C',
        ]
    }, {
        title: `We all have first impression of someone we just met. But why? (77)Why do we form an opinion about someone without really knowing anything about him or her - aside perhaps from a few remarks or readily observable traits. '
The answer is related to how your brain allows you to be aware of the world. Your brain is so sensitive in picking up facial traits, even very minor difference in a how a person^ eyes, ears, nose, or mouth are placed in relation to each other make you see him or her as different. In fact, your brain continuously processes incoming sensory information - the sights and sounds of your world. Theses incoming “signals” are compared against a host of “memories” stored in the brain areas called the cortex (大脑皮层）system to determine what these new signals “mean”.
If you see someone you know and like at school, your brain says ''familiar and safe,\ i4If you see someone new; it says, "'new—potentially threatening77. Then your brain starts to match features of this stranger with other ；iknownv memories. The height, weight, dress, ethnicity, gestures and tone of voice are all matched up. The more unfamiliar the characteristics, the more your brain may say, “This is new. I don’t like this person ” Or else，“I am intrigued.” Or your brain may perceive a new face but familiar clothes, ethnicity, gestures - like your other friends; so your brain says: "I like this person•” But theses preliminary “impressions” can be dead wrong.
When we stereotype people, we use a less mature form of thinking (not unlike the immature thinking of a very young child) that makes simplistic and categorical impressions of others. Rather than learn about the depth and breadth of people - their history, interest, values, strengths, and true character - we categorize them as jocks, geeks, or freaks.
(78)However. if we resist initial stereotypical impressions, we have a chance to be aware of what a person is truly like. If we spend time with a person, hear about his or her life, hopes, dreams,and become aware of the person's character, we use a different, more mature style of thinking—and the most complex areas of our cortex, which allow us to be humane.`,
        type: 2,
        arr: [
            '6. Our first impression of someone new is influenced by his or her',
            'A. past experience.',
            'B. charater.',
            'C. facial features.',
            'D. hobbies.',
            '答案：C',
            '7. If you meet a stranger with familiar geatures, your brain is most likely to say',
            'A. .‘He is familiar and safe.”',
            'B. “He is new and potentially threatening.”',
            'C. "I like this person"',
            'D. “This is new, I don’t like this person.”',
            '答案：C',
            '8. The word :pre mil inary” in Paragraph 3 is closet in meaning to',
            'A. simplistic.',
            'B. stereotypical.',
            'C. initial.',
            'D. categorical.',
            '答案：C',
            '9. Our thinking is not mature enough when we stereotype people because',
            'A. we neglect their depth and breadth.',
            'B. they are not all jocks, peeks, or freaks.',
            'C. our thinking is similar to that of a very young child',
            'D. our judgment is always wrong.',
            '答案：A',
            '10. Which of the following statements best expresses the main idea of the passage?',
            'A. One\'s physical appearance can influence our first impression.',
            'B. Our first impression is influenced by,the sensitivity of our brain.',
            'C. Stereotypical impressions can be dead wrong.',
            'D. We should adopt mature thinking when getting to know people.',
            '答案：B'
        ]
    }, {
        title: `It pays to be smart, but vve are not all smart in the same way. You may be a talented musician, but you might not be a good reader. Each of us is different.
Psychologists disagree about what is intelligence and what are talents or personal abilities. Psychologists have two different views on intelligence. Some believe there is one general intelligence. Others believe there are many different intelligences.
Some psychologists say there is one type of intelligence that can be measured with IQ tests. These psychologists support their view with research that concludes that people who do well on one kind of test for mental ability do well on other tests. They do well on tests using words, numbers or pictures. They do well on individual or group tests , and written or orai tests. Those who do poorly on one test, do the same on all tests.
Studies of the brain show that there is a biological basis for general intelligence. The brain of intelligence people use less energy during problem solving. Ilie brain waves of people with higher intelligence show a quicker reaction. (79)Some researchers conclude that diifcrcnces in intelligence result from differences in the speed and effectiveness of information processing by the brain.
Howard Gardner, a psychologist at the Harvard School of Education, has four children. He believes that all children are different and shouidn7t be tested by one intelligence test. Although Gardner believes general intelligence exists, he doesnH think it tells much about the talents of a person outside of formal schooling.He think that the human mind has different intelligences. These intelligences allow us to solve the kinds of problems we are presented with in life .Each of us has different abilities within these intelligences. (80)Gardncr believes that the purpose of school should be to encourage development of all of our intelligences,
Gardner says that his theory is based on biology. For example, when one part of the Brain is injured, other parts of the brain still work. People who cannot talk because of Brain damage can still sing.So, there is not just one intelligence to lose. Gardner has identified 8 different kinds of intelligence; jinguistic, mathematical, spatial, musical, interpersonal, intrapersona!, body-kinestlietic(身体动觉的)，and naturalistic .`,
        type: 2,
        arr: [
            '11. What is the main idea of this passage ?',
            'A. How to understand intelligence .',
            'B. The importance of intelligence •',
            'C. The development of intelligence tests .',
            'D. How to become intelligent.',
            '答案：A',
            '12. Which of the following statements is true concerning general intelligence ?',
            'A. Most intelligent people do well on some intelligence tests .',
            'B. People doing well on one type of intelligence test do well on other tests.',
            'C. Intelligent people do not do well on group tests .',
            'D. Intelligent people do better on written tests than on oral tests .',
            '答案：B',
            '13. Gardner believes that ,',
            'A. all children are alike.',
            'B. children should take one intelligence test',
            'C. there is no genera! intelligence. *',
            'D. children have different intelligences.',
            '答案：D',
            '14. According to Gardner, schools should',
            'A. promote development of all intelligences.',
            'B. test students\' IQs.',
            'C. train students who do poorly on tests.',
            'D. focus on finding the most inteliigent students.',
            '答案：A',
            '15. Gardner thinks that his theory has a',
            'A. musical foundation.',
            'B. intrapersonal foundation.',
            'C. linguistic foundation.',
            'D. biological foundation.',
            '答案：D',
        ]
    }, {
        title: `Directions: In this part there are 30 incomplete sentences. For each sentence there are four choices marked A, B, C and D. Choose the ONE answer that best completes the sentence. Then blacken the corresponding letter on the Answer Sheet.`,
        type: 2,
        arr: [
            '16.I_________to visit you later that day, but I had to phone and cancel.',
            'A. come ',
            'B. came ',
            'C. am coming ',
            'D. was coming',
            '答案：D',
            '17. ____ the advice of his friends, he would not have suffered such a heavy loss in his business.',
            'A. If he took ',
            'B.If he should take ',
            'C.Were he take ',
            'D.Had he taken',
            '答案：D',
            '18. My uncle hasn^ been able to quit smoking, but at least he has_______•',
            'A. cut out ',
            'B. cut down ',
            'C. cut up ',
            'D. cut off',
            '答案：B',
            '19. Finally he reached a lonely island_________was completely cut off from the outside world.',
            'A. when ',
            'B. where ',
            'C. which ',
            'D. whom',
            '答案：C',
            '20. The university estimates that living expenses for international students______________around $8,450 a year, which__________a burden for some of them.',
            'A. are； is ',
            'B. are； are ',
            'C. is； are ',
            'D. is； is',
            '答案：A',
            '21. ______at the cafeteria before, Tina didn\'t want to eat there again.',
            'A. Having eaten ',
            'B. To eat ',
            'C. Eat ',
            'D. Eating',
            '答案：A',
            '22. No longer_______in charge of this work.',
            'A. he was ',
            'B.was he ',
            'C.he does ',
            'D.does he',
            '答案：B',
            '23. ________I want to tell you is the deep love and respect I have for my parents.',
            'A. That ',
            'B. Which ',
            'C. Whether ',
            'D. What',
            '答案：D',
            '24. The girl has a great interest in sport and______badminton classes twice a week over the last three years.',
            'A.took ',
            'B. is taking ',
            'C. takes ',
            'D. has been taking',
            '答案：D',
            '25. An artist who was recently traveling on a ferry to the southern island discovered________a long lost antique Greek vase.',
            'A. at random ',
            'B. by chance ',
            'C. in turn ',
            'D. on occasion',
            '答案：B',
            '26. —Da4 I don’t think Oliver the right sort of person for the job. —I see. IMi go right away and_________•',
            'A. pay him back ',
            'B. pay him off ',
            'C.put him away ',
            'D. put him off',
            '答案：B',
            '27. “What do you want to be?” asked Mrs. Crawford. “Oh, I __________president, said the boy, with a smile.',
            'A. have been ',
            'B. am ',
            'C. was ',
            'D. will be',
            '答案：D',
            '28. Although Rosemary had suffered from a serious illness for years, she lost____________of her enthusiasm for life.',
            'A. some ',
            'B. neither ',
            'C. none ',
            'D. ail',
            '答案：C',
            '29. Four and______ half hours of discussion took us up to midnight,and_________break for cheese ,chocolate and tea with sugar.',
            'A. a;a ',
            'B. the; the ',
            'C.不填；the ',
            'D. a;不填',
            '答案：A',
            '30. In some languages, 100 words make up half of all words ___________in daily conversations.',
            'A. using ',
            'B. to use ',
            'C. having used ',
            'D. used ',
            '答案：D',
            '3l.No one__________be more generous; he was a heart of gold.',
            'A. could ',
            'B. must ',
            'C. dare ',
            'D. need',
            '答案：A',
            '32. A computer can only do________you have instructed it to do.',
            'A. how ',
            'B. after ',
            'C. what ',
            'D. when',
            '答案：C',
            '33.It was with the help of the local guide______the mountain climber was rescued.',
            'A. who ',
            'B. that ',
            'C. when ',
            'D. how',
            '答案：B',
            '34.It\'s much easier to make friends_______ you have similar',
            'A. unless ',
            'B. when ',
            'C. even though ',
            'D.so that',
            '答案：B',
            '35.I can’t meet you on Sunday. I’ll be_________occupied.',
            'A. also ',
            'B. just ',
            'C. nevertheless  ',
            'D.otherwise',
            '答案：C',
            '36.This is by far_______movie that I have ever seen.',
            'A. an inspiring ',
            'B. a much inspiring ',
            'C. the most inspiring ',
            'D. the more inspiring',
            '答案：C',
            '37,It’s a________clock, made of brass and dating from the nineteenth century.',
            'A. charming French small ',
            'B. French small charming ',
            'C. small French charming ',
            'D. charming small French',
            '答案：D',
            '38. Anyone, once___positive for H7N9 flu virus, will receive free medical treatment from our government.',
            'A. to be tested ',
            'B. being tested ',
            'C. tested ',
            'D. to test',
            '答案：C',
            '39. He is so busy. He cannot afford enough time with his son —_____he wants to.',
            'A. even if ',
            'B. as if ',
            'C. because ',
            'D. before ',
            '答案：A',
            '40. It is generally considered unwise to give a child ______ he or she wants.',
            'A.however ',
            'B. whatever ',
            'C. whichever ',
            'D. Whenever',
            '答案：B',
            '41.Lessons can be learned to face the future, ______ history cannot be changed.',
            'A.though ',
            'B. as ',
            'C. since ',
            'D. unless',
            '答案：A',
            '42 The book has helped me greatly in my daily communication, especially at work______________a good impression is a must,',
            'A. which ',
            'B. when ',
            'C. as ',
            'D. where',
            '答案：D',
            '43. ~How much do you know about the Youth Olympic Games to be held in Nanjing? —Well, the media ______it in a variety ofTorms,',
            'A. cover ',
            'B. will cover ',
            'C. have covered ',
            'D. covered',
            '答案：C',
            '44. Tom always goes jogging in the morning and he usually does push-ups too to stay_________.',
            'A. in place ',
            'B. in order ',
            'C. in shape ',
            'D. in fashion',
            '答案：C',
            '45.She was put under house arrest two years ago but remained a powerful___________in last year’s election.',
            'A. symbol ',
            'B. portrait ',
            'C. identity ',
            'D. statue',
            '答案：A',
        ]
    }, {
        title: `Directions: Each of the following senlences has four underlined parts marked A, B, C and D. Identify the one that is not correct. Then blacken the corresponding tetter on the Answer Sheet`,
        type: 2,
        arr: [
            '46.Yuan Long ping <em class="col-red">(takes up)</em> research <em class="col-red">(on)</em> farming <em class="col-red">(for decades)</em> and this is <em class="col-red">(which)</em> he devotes all hislife to.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：D',
            '47,<em class="col-red">(To observe)</em> carefully if <em class="col-red">(any)</em> change occurs when <em class="col-red">(doing)</em> experiments <em class="col-red">(in the lab)</em>.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：A',
            '48.<em class="col-red">(lt)</em> was the middle of the night <em class="col-red">(that)</em> my father <em class="col-red">(woke me)</em> up and told me <em class="col-red">(to watch)</em> the football game.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：B',
            '49.Good families are <em class="col-red">(much)</em> to <em class="col-red">(all)</em> <em class="col-red">(their)</em> members, but <em class="col-red">(something)</em> to none.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：D',
            '50.<em class="col-red">(The manager)</em> was satisfied <em class="col-red">(to see)</em> many new products <em class="col-red">(develop)</em> after <em class="col-red">(great effort)</em>,',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '51. A company <em class="col-red">(which)</em> profits <em class="col-red">(from)</em> markets <em class="col-red">(are declining)</em> may seek opportunities <em class="col-red">(abroad)</em>.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：A',
            '52.He is thought <em class="col-red">(to act)</em> <em class="col-red">(Foolishly)</em>. Now he has on one <em class="col-red">(but)</em> himself <em class="col-red">(to blame)</em> for losing the job.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：A',
            '53.<em class="col-red">(Lessons)</em> can be learned to <em class="col-red">(face the future)</em>, <em class="col-red">(since)</em> history <em class="col-red">(cannot)</em> be changed.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '54.<em class="col-red">(There,s)</em> a note <em class="col-red">(pinned to)</em> the door <em class="col-red">(says)</em> when the shop will <em class="col-red">(open)</em> again.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '55.<em class="col-red">(Look out!)</em> Don’t get <em class="col-red">(too)</em> close to the house <em class="col-red">(of which)</em> roof is <em class="col-red">(under repair)</em>,',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
        ]
    }, {
        title: `One night, when I was eight, my mother gently asked me a question I wuld never forget. ^Sweetie, my company wants to <em class="col-red">____56____</em> me but needs me to work in Brazil. This is iike your teacher telling that you?ve done <em class="col-red">____57____</em> and allowing you to skip a grade(跳级)，but you’丨 1 have to <em class="col-red">____58____</em> your friends. Would you say yes to your teacher?^ She gave me a hug and asked me to think about it. I was puzzled. The question kept me <em class="col-red">____59____</em> for the rest of the night I had said uyes^ but for the first time, I realized the <em class="col-red">____60____</em> decisions adults had to make.`,
        type: 2,
        arr: [
            '56. ',
            'A. attract ',
            'B. promote ',
            'C. surprise ',
            'D. praise',
            '答案：B',
            '57. ',
            'A. littfe ',
            'B. much ',
            'C. well ',
            'D. wrong',
            '答案：C',
            '58. ',
            'A. leave ',
            'B. refuse ',
            'C. contact ',
            'D. forgive',
            '答案：A',
            '59. ',
            'A. explaining ',
            'B. sleeping ',
            'C. wondering ',
            'D. regretting',
            '答案：C',
            '60. ',
            'A. poor ',
            'B. timely ',
            'C. final ',
            'D. tough',
            '答案：D',
        ]
    }, {
        title: `For almost four years, my mother would call us from Brazil every day. Every evening Vd <em class="col-red">____61____</em> wait for the phone to ring and then tell her every detail of my day. A phone call, however, could never replace her <em class="col-red">____62____</em> and it was difficult not to feel lonely at times.
        During my fourth-grade Christmas break, we flew to Rio to visit her. Looking at her large <em class="col-red">____63____</em> apartment, I became <em class="col-red">____64____</em> how lonely my mother must have been in Brazil herself. It was then <em class="col-red">____65____</em>`,
        type: 2,
        arr: [
            '61. ',
            'A. eagerly ',
            'B. politely ',
            'C. nervously ',
            'D. curiousty',
            '答案：A',
            '62. ',
            'A. patience ',
            'B. presence ',
            'C. intelligence ',
            'D. Influence',
            '答案：B',
            '63. ',
            'A. Comfortable ',
            'B. Expensive ',
            'C. Empty ',
            'D. Modern',
            '答案：C',
            '64. ',
            'A. Interested in ',
            'B. aware of ',
            'C. doubtful ',
            'D. satisfied with',
            '答案：B',
            '65. ',
            'A. when ',
            'B. where ',
            'C. which ',
            'D. that',
            '答案：D',
        ]
    }, {
        title: `I started to appreciate the tough choices she had to make on <em class="col-red">____66____</em> family and work. <em class="col-red">____67____</em> difficult decisions, she used to tell me, you wouldn't know whether you make the right choice, but you could always make the best out of the situation, with passion and a <em class="col-red">____68____</em>_attitude.
        Back home , I <em class="col-red">____69____</em> myself that what my mother could do. I could, too. If she <em class="col-red">____70____</em> to live in Rio all by herself,`,
        type: 2,
        arr: [
            '66. ',
            'A. abandoning ',
            'B. balancing ',
            'C. comparing ',
            'D. mixing',
            '答案：B',
            '67„ ',
            'A. Depending on ',
            'B. supplied with ',
            'C. Faced with ',
            'D. Insisting on',
            '答案：C',
            '68. ',
            'A. different ',
            'B. friendly ',
            'C. positive ',
            'D. general',
            '答案：C',
            '69. ',
            'A. criticized ',
            'B. informed ',
            'C. warned ',
            'D. reminded',
            '答案：D',
            '70. ',
            'A. managed ',
            'B. offered ',
            'C. attempted ',
            'D. expected',
            '答案：A',
        ]
    }, {
        title: `I, too, could learn to be <em class="col-red">____71____</em> ,1 learn how to take care of myself and set high but achievable <em class="col-red">____72____</em>. My mother is now back with us. But J will never forget what the <em class="col-red">____73____</em> has really taught me.Sacrifices <em class="col-red">____74____</em> in the end. The separation between us has proved to be <em class="col-red">____75____</em> for me.`,
        type: 2,
        arr: [
            '71. ',
            'A. grateful ',
            'B. energetic ',
            'C. independent ',
            'D. practical',
            '答案：C',
            '72. ',
            'A. examples ',
            'B. limits ',
            'C. rules ',
            'D. goals',
            '答案：D',
            '73. ',
            'A. question ',
            'B.experience ',
            'C. history ',
            'D. occasion',
            '答案：B',
            '74. ',
            'A. pay off ',
            'B. come back ',
            'C. run out ',
            'D. turn up',
            '答案：A',
            '75. ',
            'A. blessing ',
            'B. gathering ',
            'C. failure ',
            'D. pleasure',
            '答案：A',
        ]
    }
]