window.readingJson = [
    {
        title: `Wealtii starts with a goal and saving a dollar at a time. Call it the piggy bank strategy .
        There are lessons in that time-honored coin-sayings container.
        Any huge task seems easier when reduced to baby steps. If you wished to climb a 12,000-foot mountain, and could do it a day at a time, you would only have to climb 33 feet daily to reach the top in a year. If you want to take a really nice trip in 10 years for a special occasion, to collect the $15,000 cost, you have to save $ 3.93 a day. If you drop that into a piggy bank and then once a year put $1,434 in a savings account at 1% interestrate after-tax, you will have your trip money.
        r76)When T was a child, mv parents gave me a piggy bank to teach me that, if I wanted something, I should save money to buy it. We associate piggy banks with children, but in many countries, the little containers are also popular with adults, Europeans see a piggy bank as a sign of good fortune and wealth. Around the world, many believe a gift of a piggy bank on New Year's Day brings good luck and financial success. Ah, yes, but you have to put something in it。
        Why is a pig used as a symbol of saving? Why not an elephant bank, which is bigger and holds more coins? In the Middle Ages, before modern banking and credit instruments, people saved money at home, a few doms at a time dropped into a jar or dish- Potters (制陶工）made these inexpensive containers from an orange-colored clay called "pygg/'- and folks saved
        coins in pygg jars. The Middle English word for pig was "pigge. H While the Saxons pronounced pygg, referring to the day, as Hpug,M eventually the two words changed into the same pronunciation, sounding the Min as in pig or piggy. As the word became less associated with the orange clay and more with the animal, a clever potter fashioned a pygg jar in the shape of a pig, delighting children and adults. The piggy bank was born.
        (77)Qriginalty you had to break the bank to get to the money, bringing in a sense of seriousness into savings. While piggy banks teach children the wisdom of saving, adults often need to relearn childhood lessons. Think about the things in life that require large amounts of money — college education, weddings, cars, medical care, starting a business, buying a home, and fun stuff like great trips. So when you have money, take off the top 10%, put it aside, save and invest wisely.`,
        type: 2,
        arr: [
            '1. What is the piggy bank strategy?',
            'A. Paying 1% income tax at a time.',
            'B. Setting a goal before making a travel plan.',
            'C. Aiming high even when doing small things.',
            'D. Putting aside a little money regularly for future use.',
            '答案：D',
            '2. Why did the writer\'s parents give him a piggy bank as a gift?',
            'A. To delight him with the latest fashion.',
            'B. To encourage him to climb mountains.',
            'C. To help him form the habit of saving.',
            'D. To teach him English pronunciation.',
            '答案：C',
            '3. What does the underlined word “something”（Paragraph 3) most probably refer to?',
            'A. Money.',
            'B. Gifts.',
            'C. Financial success.',
            'D. Good luck.',
            '答案：A',
            '4. The piggy bank originally was',
            'A. a potter\'s instrument.',
            'B. a cheap clay container. .',
            'C. an animal-shaped dish.',
            'D. a pig-like toy for children.',
            '答案：B',
            '5. The last paragraph talks about',
            'A. the seriousness of educating children.',
            'B. the enjoyment of taking a great trip.',
            'C. the importance of managing money .',
            'D. the difficulty of starting a business.',
            '答案：C',
        ]
    }, {
        title: `Last summer, two nineteenth-century cottages were rescued from remote farm fields in Montana, to he moved to an Art Deco building in San Francisco. The houses were made of wood. These cottages once housed early settlers as they worked the dry Montana soil; now they hold Twitter engineers.
        The cottages could be an example of the industry’s odd love affair with "low technology," a concept associated with the natural world，and with old-school craftsmanship (手艺）that exists long before the Internet era. Low technology is not virtual (虚拟的so, to take advantage of it, Internet companies have had to get creative. The rescued wood cottages, fitted by hand in the late eighteen-hundreds, are an obvious example, but Twitter's designs lie on the extreme end. Other companies are using a broader interpretation (jfl#) of low technology that focuses on nature.
        (78)Amazon is building three glass spheres filled with trees, so that employees can ctwork and socialize in a more natural, park-like setting.At Google’s office，an entire floor is carpeted in grass. Facebook's second Menlo Park campus will have a rooftop park with a walking trail.
        OJle Lundberg, the founder of Lundberg Design, has worked with many tech companies over
        the years. MWe have lost the connection to the maker in our lives, and our tech engineers are the
        2/10
        ones who feel most impoverished(贫乏的X because they’re surrounded by the digital world，” he says. "They're looking for a way to regain their individual identity, and weVe found that introducing real crafts is one way to do that H
        This craft-based theory is rooted in histotry. William Morris, the English artist and writer, turned back to pre-industrial arts in the eighteen-sixties, just after the Industrial Revolution, The Arts and Crafts movement defmeii itself against machines, M Without creative human occupation, people became disconnected from life,11 Morris s^id.
        Research has shown that natural environments can restore (Ucft) our mental capacities. In Japan, patients are encouraged to 'Torest-bathe^ taking walks through woods to lower their blood pressure.
        These health benefits apply to the workplace as well. Rachel Kaplan, a professor of environmental psychology, has spent years researching the restorative effects of natural environments. Her research found that workers with access to nature at the office — even simple views of trees and flowers — felt their jobs were less stressflil and more satisfying. If low-tech offices can potentially nourish the brains and improve the mental health of employees then, fine, bring on the cottages*`,
        type: 2,
        arr: [
            '6. The writer mentions the two nineteenth-century cottages to show that',
            'A. Twitter is having a hard time. ,',
            'B. old cottages are in need of protection,',
            'C. early settlers once suffered from a dry climate in Montana,',
            'D. Internet companies have rediscovered the benefits of low technology.',
            '答案：D',
            '7. Low technology is regarded as something that',
            'A. is related to nature.',
            'B. is out of date today,',
            'C. consumes too much energy.',
            'D. exists in the virtual world,',
            '答案：A',
            '8. The main idea of Paragraph 5 is that human beings',
            'A, have destroyed many pre-industrial aits.',
            'B, have a tradition of valuing arts and crafts.',
            'C. can become intelligent by learning history.',
            'D. can regain their individual identity by using machines,',
            '答案：B',
            '9. The writer^ attitude to 41ow technology^ can best be described as',
            'A. positive, ',
            'B. defensive, ',
            'C. cautious.',
            'D. doubtful,',
            '答案：A',
            '10. What might be the best title for the passage?',
            'A. Past Glories, Future Dreams,',
            'B. The Virtual World, the Real Challenge.',
            'C. High-tech Companies, Low-tech Offices.',
            'D. The More Craftsmanship, the Less Creativity*',
            '答案：C',
        ]
    }, {
        title: `(79)A city child's summer is spent in the street in front of his home, and ail through the long summer vacations I sat on the edge of the street and watched enviously the other boys on the block play baseball. I was never asked to take part even when one team had a member missing— not out of special cruelty, but because they took it for granted I would be no good at it. They were right, of course.
        I would never forget the wonderful evening when something changed. The baseball ended about eight or eight thirty when it grew dark. Then it was the custom of the boys to retire to a little stoop (ll/iE) that stuck out from the candy store on the corner and that somehow had become theirs. No grownup ever sat there or attempted to. There the boys would sit, mostly talking about the games played during the day and of the game to be played tomorrow. Then long silences would fall and the boys would wander off one by one. It was just after one of those long silences that my life as an outsider changed. I can no longer remember which boy it was that summer evening who broke the silence with a question; but whoever he was, I nod to him gratefully now. "What’s in those books you're always reading?” he asked casually. "Stories，" I answered. "What kind?" asked somebody else without much interest.
        Nor do I know what drove me to behave as I did, for usually I just sat there in silence, glad enough to be allowed to remain among them; but instead of answering his question, I told them for two hours the story I was reading at the moment. The book was Sister Carrie. They listened bug-eyed and breathless. I must have told it well, but I think there was another and deeper reason that made them so keen an audience. Listening to a tale being told in the dark is one of the most
        A
        ancient of man's entertainments, but I was offering them as well, without being aware of doing it, a new and exciting experience.
        The books they themselves read were the Rover Boys or Tom Swift or G A. Henty. I had read them too, but at thirteen I had long since left them behind. (8Q)Since I was much alone I had become an enthusiastic reader and I had gone through the books-for-bovs- series. In those days there was no reading material between children’s and grownups’ books，or I could find none。I had gone right from Tom Swift and His Flying Machine to Theodore Dreiser and Sister Carrie, Dreiser had hit my young mind, and they listened to me tell the story with some of the wonder that I had had in reading it
        The next night and many nights thereafter, a kind of unspoken ritual (仪式）took placeD As it
        grew dark, I would take my place in the center of the stoop and begin the evening1 s tale. Some
        nights, in order to taste my victory more completely, I cheated. I would stop at the most exciting
        part of a story by Jack London or Bret Harte, and without warning tell them that that was as far as
        I had gone in the book and it would have to be continued the following evening. It was not true, of
        course; but I had to make certain of my new-found power and position. I enjoyed the long summer
        evenings until school began in the fall. Other words of mine have been listened to by larger and
        more fashionable audiences, but for that tough and athletic one that sat close on the stoop outside the candy store, I have an unreasoning love that will last forever.`,
        type: 2,
        arr: [
            '11. Watching the boys playing baseball, the writer must have felt',
            'A. bitter and lonely.',
            'B. special and different',
            'C. pleased and excited.',
            'D. disturbed and annoyed.',
            '答案：A',
            '12. The writer feels grateful even now to the boy who asked the question because the boy',
            'A. invited him to join in their game.',
            'B. liked the book that he was reading.',
            'C. broke the long silence of that summer evening.',
            'D. offered him an opportunity that changed his. life.',
            '答案：D',
            '13. According to Paragraph 3, story-telling was popular among the boys basically because',
            'A. the story was from a children^ book.',
            'B. listening to tales was an age-old practice.',
            'C. the boys had few entertainments after dark.',
            'D. the boys didn\'t read books by themselves.',
            '答案：B',
            '14. The boys were attracted to Sister Carrie because',
            'A. it was written by Theodore Dreiser.',
            'B. it was specifically targeted at boys.',
            'C. it gave them a deeper feeling of pleasure.',
            'D. it talked about the wonders of the world.',
            '答案：C',
            '15. Sometimes the writer stopped at the most exciting part of a story to .',
            'A. play a mean trick on the boys.',
            'B. experience more joy of achievement.',
            'C. add his own imagination to the story.',
            'D. help the boys understand the story better.',
            '答案：B',
        ]
    }, {
        title: `In this part there are 30 incomplete sentences. For each sentence there are four choices marked A, Bt C and D. Choose the ONE answer that best completes the sentence. Then blacken the corresponding letter on the Answer Sheet.`,
        type: 2,
        arr: [
            '16. Many countries are now setting up national parks __________________ animals and plants can be protected.',
            'A. when ',
            'B. which ',
            'C. whose ',
            'D. where',
            '答案：D',
            '17. ______ in the early 20th century, the school keeps on inspiring children’s love of art.',
            'A. To found ',
            'B. Founding ',
            'C. Founded ',
            'D. Having founded',
            '答案：C',
            '18.It was not until near the end of the letter_____________she mentioned her own plan.',
            'A. that ',
            'B. where ',
            'C. why ',
            'D. when',
            '答案：A',
            '19. Don,t turn off the computer before closing all programs _________ you could have problems.',
            'A. or ',
            'B. and ',
            'C. but ',
            'D. so',
            '答案：A',
            '20. He didn’t selfishly keep for himself the money inherited from his uncle. Instead, he made a______ contribution to help the community.',
            'A. commercial ',
            'B. generous ',
            'C. comparable ',
            'D. profitable',
            '答案：B',
            '21 .When I was a child, I___________watch TV whenever I wanted to.',
            'A.should ',
            'B. could ',
            'C.must ',
            'D.need',
            '答案：B',
            '22. The room is empty except for a bookshelf_______in one corner',
            'A. standing ',
            'B. to stand ',
            'C. stands ',
            'D. stood',
            '答案：A',
            '23. When the group discussion is nearing its end, make sure to____it with important point. ',
            'A. conclude ',
            'B. lead ',
            'C. avoid ',
            'D. Hold',
            '答案：A',
            '24,If we leave right away,________we’ll arrive cm time.',
            'A. hopefully ',
            'B. curiously ',
            'C. occasionally ',
            'D. Gradually',
            '答案：A',
            '25. Maiy worked here as a_________ secretary and ended up getting a full-time job with the company*',
            'A. pessimistic ',
            'B. temporary ',
            'C. previous ',
            'D. cautious',
            '答案：B',
            '26, General Blair had been in the army ______for 35 years when he retired from the army.',
            'A. service ',
            'B.work',
            'C. job ',
            'D.homework',
            '答案：A',
            '27 Jane is in a hurry because the train to the airport leaves___________half an hour.',
            'A. by ',
            'B. in ',
            'C. for ',
            'D. until',
            '答案：B',
            '28.It will be a big help if you go to the store and get what we need for dinner.____________, I\'ll set the table.',
            'A. As a result ',
            'B. On the whole ',
            'C. In the meanwhile ',
            'D. As a matter of fact',
            '答案：C',
            '29. Bears________fat stores throughout the summer and fall to have enough energy to last them through their winter sleep,',
            'A. pack up ',
            'B. build up ',
            'C. bring up ',
            'D. take up',
            '答案：B',
            '30. Every thing seemed to be going ______for the first two days after I moved to New York,',
            'A. vividly ',
            'B. generally ',
            'C. frequently ',
            'D. smoothly',
            '答案：D',
            '31 .Top graduates from universities are__________by major companies.',
            'A. chased ',
            'B. registered ',
            'C. offered ',
            'D. compensated',
            '答案：A',
            '32. —It rained cats and dogs this morning. Fm glad we took an umbrella* —Yeah，we would have got wet all over if we_______；',
            'A. hadn’t ',
            'B.Haven’t ',
            'C. Didn’t ',
            'D. Don’t',
            '答案：A',
            '33. --- So what is the procedure? —All the applicants_______ before a final decision is made by the authority.',
            'A.interview ',
            'B. are interviewing ',
            'C. are interviewed ',
            'D. are being interviewed',
            '答案：C',
            '34. I‘m calling about the apartment you_________ the other day. Could you tell me more about it?',
            'A.advertised ',
            'B. had advertised ',
            'C. are advertising ',
            'D. will advertise',
            '答案：A',
            '35,There’re few apples in the basket, _________?',
            'A.are  there ',
            'B.aren’t there ',
            'C.do there ',
            'D.will there',
            '答案：A',
            '36.Would you like to_______with us to the film tonight?',
            'A. come along ',
            'B. come off ',
            'C. come across ',
            'D. come through',
            '答案：A',
            '37.It’s not easy to change habits,_______with awareness and self-control, it is possible.',
            'A. for ',
            'B. or ',
            'C. but ',
            'D. so',
            '答案：C',
            '38. The idea “happiness，’’ —______, will not sit still for easy definition.',
            'A. to be rigid ',
            'B. to be sure ',
            'C. to be perfect ',
            'D. to be fair',
            '答案：B',
            '39. —________! Somebody has left the lab door open, ——Don’t look at me，',
            'A. Dear me ',
            'B. Hi, there ',
            'C. Thank:goodness ',
            'D. Come on',
            '答案：A',
            '40. 一 Oh no! We’re too late. The train ______. —That’s OL We’ll catch the next train to London.',
            'A. was leaving ',
            'B. had left ',
            'C. has left ',
            'D. has been leaving',
            '答案：C',
            '41. When I arrived, Bryan took me to see the house _____ I would be stayinga',
            'A. what ',
            'B. when ',
            'C. where ',
            'D. which',
            '答案：C',
            '42. The parents were shocked by_____ news that their son needed_______operation on his knee.',
            'A. a; / ',
            'B. the; / ',
            'C. the; an ',
            'D. a; an',
            '答案：C',
            '43. Mark needs to learn Chinese________his company is opening a branch in Beijing,',
            'A. unless ',
            'B. until ',
            'C. although ',
            'D. since',
            '答案：D',
            '44. — Is Arme coming tomorrow? —______If she were to come, she would have called me.',
            'A. Go ahead ',
            'B. Certainly ',
            'C. That’s right ',
            'D.l don’t think so',
            '答案：D',
            '45.1 don^ really like the author, ___________ I have to admit his books are very exciting.',
            'A. although ',
            'B. unless ',
            'C. until ',
            'D. once',
            '答案：A'
        ]
    }, {
        title: `Directions; Each of the following sentences has four underlined parts marked A, B, C and D. Identify the one that is not correct Then blacken the corresponding letter on the Answer Sheet 46-55`,
        type: 2,
        arr: [
            '46. We <em class="col-red">(have launched)</em> <em class="col-red">(another)</em> man-made satellite, <em class="col-red">(what)</em> is announced in <em class="col-red">(today\'s)</em> newspaper.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '47. <em class="col-red">(Driving)</em> <em class="col-red">(with)</em> care, the car can <em class="col-red">(serve)</em> you <em class="col-red">(more)</em> than ten years.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：A',
            '48. You <em class="col-red">(had)</em> better stop <em class="col-red">(smoking)</em>, <em class="col-red">(but)</em> your health will <em class="col-red">(break down)</em>,',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '49. Last night, there <em class="col-red">(were)</em> millions of people <em class="col-red">(to watch)</em> the <em class="col-red">(opening)</em> ceremony <em class="col-red">(live)</em> on TV',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：B',
            '50. He finds <em class="col-red">(it)</em> easier to do the <em class="col-red">(cooking)</em> himself than <em class="col-red">(teaching)</em> his wife <em class="col-red">(to cook)</em>,',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '51 .She <em class="col-red">(had lived)</em> in London and Manchester, <em class="col-red">(but)</em> she liked <em class="col-red">(either)</em> and <em class="col-red">(moved to)</em> Cambridge.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '52. <em class="col-red">(Was it)</em> because Jack came <em class="col-red">(late for)</em> school <em class="col-red">(why)</em> Mr.Smith <em class="col-red">(got angry)</em>?',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '53.Susan made <em class="col-red">(that)</em> clear <em class="col-red">(to me)</em> that she wished <em class="col-red">(to make)</em> a new life <em class="col-red">(for)</em> herself.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：A',
            '54. We <em class="col-red">(had better)</em> <em class="col-red">(struggled)</em> for the future <em class="col-red">(rather than)</em> regret <em class="col-red">(for)</em> the past. life to.',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：B',
            '55.They <em class="col-red">(made up)</em> their mind <em class="col-red">(that)</em> they <em class="col-red">(bought)</em> a new house <em class="col-red">(once)</em> Larry changed jobs。',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
        ]
    }, {
        title: `One day, Marissa noticed a spider web, shining in the sunlight. A spider was spinning <em class="col-red">____56____</em> on it The spider wasn^ trying to be something else, like a butterfly or a bee, Marissa thought. It was happy to be exactly what it was and to do what it was good at. What came naturally to Marissa was <em class="col-red">____57____</em>. She could paint or draw all day long and never get bored. However, a few weeks ago Marissa signed up for high jump. Because her mother had been a high jump <em class="col-red">____58____</em> in school, she thought it would make her mother happy. But now she <em class="col-red">____59____</em> that however hard she worked, she would never be a high jump star like her mother. One night, halfway through her homework, Marissa fell <em class="col-red">____60____</em> .`,
        type: 2,
        arr: [
            '56. ',
            'A. webs',
            'B. clothes',
            'C. balls',
            'D. boxes',
            '答案：A',
            '57. ',
            'A. music',
            'B. art',
            'C. sport',
            'D. dance',
            '答案：B',
            '58.',
            'A. coach',
            'B. fan',
            'C.teacher',
            'D. star',
            '答案：D',
            '59. ',
            'A. realized',
            'B. wondered',
            'C. insisted',
            'D. remembered',
            '答案：A',
            '60. ',
            'A. ill',
            'B. silent',
            'C. asleep',
            'D. apart',
            '答案：C'
        ]
    }, {
        title: `When she woke up, the clock read i :00 A.M. Marissa got into a panic. There was still so much <em class="col-red">____61____</em> to do, but she really needed her rest for track practice. Marissa had always been a good student, but now track was risking her <em class="col-red">____62____</em> .
        Then a dark thought crossed Marissa^ mind. If she <em class="col-red">____63____</em> some of her classes, she would be off the track team. That was one way to solve her problem.
        After a week of <em class="col-red">____64____</em> her homework, letters had been mailed out to parents listing grades, and Marissa knew the letters would show that her grades had <em class="col-red">____65____</em> a lot.`,
        type: 2,
        arr: [
            '61. ',
            'A. homework',
            'B.research',
            'C. housework',
            'D。practice',
            '答案：A',
            '62. ',
            'A. health',
            'B. life',
            'C. grades',
            'D. images',
            '答案：C',
            '63. ',
            'A. gave',
            'B. took',
            'C. attended',
            'D, failed',
            '答案：D',
            '64. ',
            'A. completing',
            'B. ignoring',
            'C. preparing',
            'D.copying',
            '答案：B',
            '65. ',
            'A. risen',
            'B. meant',
            'C. dropped',
            'D. improved',
            '答案：C',
        ]
    }, {
        title: `She walked home with slow heavy steps, knowing her <em class="col-red">____66____</em> plan had worked.
        Just as Marissa had <em class="col-red">____67____</em> , her mother was waiting with the <em class="col-red">____68____</em> in her hand。“What’s
        happening to your grades? And more importantly, what’s happening to you?” she asked
        With tears in her eyes, Marissa admitted her <em class="col-red">____69____</em> . stI only joined the track team to make
        you proud of me. I hated it <em class="col-red">____70____</em> I didn^ want to disappoint you. I thought if I were failing in my classes,`,
        type: 2,
        arr: [
            '66. ',
            'A. ugly',
            'B. perfect',
            'C. simple',
            'D. serious',
            '答案：A',
            '67. ',
            'A. doubted',
            'B. suspected',
            'C. acted',
            'D. said',
            '答案：B',
            '68. ',
            'A. painting',
            'B. clock',
            'C. phone',
            'D. letter',
            '答案：D',
            '69. ',
            'A. feeling',
            'B. weakness',
            'C.secret',
            'D. excuse',
            '答案：C',
            '70. ',
            'A. and',
            'B. so',
            'C. or',
            'D. but',
            '答案：D',
        ]
    }, {
        title: `Coach would kick me off the team. What a <em class="col-red">____71____</em> I’ve made of everything.” Marissa watched her mother’s face turn from anger to <em class="col-red">____72____</em> • “Marissa, I was always proud of you. You didn’t need to do the high jump to make me happy。Now you have a lot of hard work in front of you because you made a bad <em class="col-red">____73____</em> Marissa thought again about the spicier. She realized she had lost sight of her <em class="col-red">____74____</em> and twisted her web. Now she had to go back and <em class="col-red">____75____</em> that web.`,
        type: 2,
        arr: [
            '71. ',
            'A. surprise',
            'B. scare',
            'C. mess',
            'D. joke',
            '答案：C',
            '72. ',
            'A. delight',
            'B. concern',
            'C. embarrassment',
            'D. disappointment',
            '答案：B',
            '73. ',
            'A. speech',
            'B. stop',
            'C. jump',
            'D. choice',
            '答案：D',
            '74. ',
            'A. balance',
            'B. example',
            'C. purpose',
            'D. success',
            '答案：C',
            '75. ',
            'A. rebuild',
            'B. break',
            'C find',
            'D. review',
            '答案：A',
        ]
    }
]