window.readingJson = [
    {
        title: `It was a cold winter day woman drove up to the Rainbow Bridge tolfbooth (收费站)_ “I’m paying for myself, and for the six cars behind me,^ she said with a smile, handing over seven tickets. (76)One after another, the next six drivers arriving at the tollbooth were informed, "'Some lady up ahead already paid your fare."
It turned out that the woman, Matalie Smith, had read something on a friend^ refrigerator: ''Practice random kindness and senseless acts of beauty.^ The phrase impressed her so much that she copied it down. ^
Judy Foreman spotted the same phrase on a warehouse wall far away from home. When it stayed on her mind for days, she gave up and drove all the way back to copy it down. thought it was beautify，” she said，explaining why she’d taken to writing it at the bottom of aH her letters， ulike a message from above/7 Her husband, Frank, liked the phrase so much that he put it up on the classroom wall for his students, one of whom was the daughter of Alice Johnson, a local news reporter. Alice put it in the newspaper, admitting that though she liked it she didn^ know where it came from or what it really meant.
Two days !ater, Alice got a c幺H from Anne Herbert, a woman living in Marin. It was in a restaurant that Anne wrote the phrase down on a piece of paper, after turning it around in iier mind for days.
“Here’s the idea，” Anne says. “Anything you think there should be more of, do it randomly。，’ Her fantasies include painting the classrooms of shabby schools, leaving hot meals on kitchen tables in the poor part of town, and giving money secretly to a proud old lady. Anne says, ''Kindness can build on itself as much as violence can."
The acts of random kindness spread. (77)If you were one of those drivers who found your fare paid, who knows what you might have been inspired to do for someone else later. Like all great events, kindness begins slowly, with every single act, Let it be yours!`,
        type: 2,
        arr: [
        '1. Why did Natalie Smith pay for the six cars behind her?',
        'A. She knew the car drivers well.',
        'B. She wanted to show kindness.',
        'C. She hoped to please others.',
        'D. She had seven tickets.',
        '答案：B',
        '2. Judy Foreman copied down the phrase because she',
        'A. thought it was beautifully written.',
        'B. wanted to know what it really meant.',
        'C. decided to write it on a warehouse wall.',
        'D. wanted her husband to put it up In the classroom.',
        '答案：A',
        '3. Who came up with the phrase according to the passage?',
        'A. Judy Foreman*',
        'B. Natalie Smith.',
        'C. Alice Johnson.',
        'D. Anne Herbert.',
        '答案：D',
        '4. Which of the following statements is closest in the meaning to the underlined sentence above?',
        'A. Kindness and violence cm change the world.',
        'B. Kindness and violence can aflfect omfs behavior. ^',
        'C. Kindness and violence can reproduce themselves,',
        'D. Kindness and violence can shape one5s character. *',
        '答案：C',
        '5. What can we infer from the last paragraph?',
        'A. People should practice random kindness to those in need.',
        'B. People who receive kindness are likely to offer it to others.',
        'C. People should practice random kindness to strangers they meet',
        'D. People who receive kindness are likely to pay it back to the given',
        '答案：B',
        ]
    },
    {
        title: `(78)Like many new graduates, i left university full of hope for the future but with m real idea of what I wanted to do. My degree, with honors, in English literature had not really prepared me for anything practical, I knew I wanted to make a difference in the world somehow, but I had no idea how to do that. Thafs when I learned about the Lighthouse Project.
I started my journey as a Lighthouse Project volunteer by reading as much as I could about the experiences of previous volunteers, I knew it would be a lot of hard work, and that I would be away from my family and friends for a very long time. In short, f did not take my decision to apply for the Lighthouse Project lightly. Neither did my family,
Eventually, however, I woo the support of my family, and I sent in all the paperwork needed for the application. After countless interviews and presentations, F managed to stand out among the candidates and survive the test alone. Several months later, l finally received a call asking me to report for the duty. I would be going to a small village near Abuja, Nigeria. Where? What? Nigeria? 1 had no idea. But I was about to find out,
After completing my training, I was sent to the village that was small and desperately in need of proper accommodation. (79)Though the local villagers were poor, they oftered their homes, hearts, and food as if I were their own family. I was asked to lead a small team of local people in building a new schooihouse. For the next year or so, I taught in that same schoolhouse. But I sometimes think I learned more from my students than they did from me.
Sometime during that period, I realized that all those things that had seemed so strange or unusual to me no longer did, though I did not get anywhere with the local language, and returned to the United States a different man. The Lighthouse Project had changed my life forever.`,
        type: 2,
        arr: [
        '6. What do we icnow about the author?',
        'A. His university education focused on the theoretical knowledge.',
        'B. His dream at university was to become a volunteer.',
        'C. He took pride in having contributed to the world.',
        'D. He felt honored to study English literature.',
        '答案：A',
        '7. According to the Paragraph 2, it is most likely that the author',
        'A. discussed his decision with his family.',
        'B. asked previous volunteers about voluntary work.',
        'C. attended special training to perform difficult tasks.',
        'D. felt sad about having to leave his family and friends.',
        '答案：A',
        '8. In his application for the volunteer job, the author',
        'A. participated in many discussions.',
        'B. went through challenging survival tests.',
        'C. wrote quite a few paper on voluntary work.',
        'D. faced strong competition from other candidates.',
        '答案：D',
        '9. On arrival at the village, the author was',
        'A. asked to lead a farming team.',
        'B. sent to teach in a schoolhouse. ',
        'C. received warmly by local villagers.',
        'D. arranged to live in a separate house.',
        '答案：C',
        '10. What can we infer from the author’s experiences in Nigeria?',
        'A. He found some difficulty adapting to the local culture.',
        'B。 He hadlearned to communicate in the local language.',
        'C. He had overcome all his weaknesses before he left for home.',
        'D. He was chosen as the most respectable teacher by his students.',
        '答案：A',
        ]
    },{
        title: `Scientists today are making greater effort t(5 study ocean currents (洋、流）.Most do it using satellites and other high-tech equipment. {8Q)However, ocean expert Curtis Hbbesmeyer does it in a special wav --- by studying movements of random floating garbage. A scientist with many years1 experience, he started this type of research in the early 1990s when he heard about hundreds of athletic shoes washing up on the shores of the northwest coast of the United States. There were so many shoes that people were setting up swap meets to try and match left and right shoes to sell or wear.
Ebbesmeyer found out in his researches that the shoes — about 60,000 in total — fell into the ocean in a shipping accident. He phoned the shoe company and asked if they wanted the shoes back. As expected，the company told him that they didn’t. Ebbesmeyer realized this could be a great experiment. If he learned when and where the shoes went into the water and tracked where they landed, he could learn a lot about the patterns of ocean currents.
The Pacific Northwest is one of the world’s best areas for beachcombing(海滩搜寻）because winds and currents join here, and as a result, there is a group of serious beachcombers in the area. Ebbesmeyer got to know a lot of them and asked for their help in collecting information about where the shoes landed. In a year he collected reliable information on 1, 600 shoes. With this data, he and a colleague were able to test and improve a computer program designed to model ocean currents, and publish the findings of their study. .
As the result of his work, Ebbesmeyer has become known as the scientist to call with questions about any unusual objects found floating in the ocean. He has even started an association of beachcombers and ocean experts, with 500 subscribers from West Africa to New Zealand. They have recorded all lost objects ranging from potatoes to golf gloves.`,
        type: 2,
        arr: [
        '11. The underlined phrase swap meets in Paragraph l is closest in meaning to',
        'A. fitting rooms.',
        'B. trading fairs. ',
        'C. business talks.',
        'D. group meetings.',
        '答案：B',
        '12. Ebbesmeyer phoned the shoe company to find out',
        'A. what caused the shipping accident.',
        'B. when and where the shoes went missing.',
        'C. whether it was all right to use their shoes.',
        'D. how much they lost in the shipping accident.',
        '答案：C',
        '13. How did Ebbesmeyer prove his assumption?',
        'A. By collecting information from beachcombers.',
        'B. By studying the shoes found by beachcomber.',
        'C. By searching the web for ocean currents models.',
        'D. By researching ocean currents data in the library.',
        '答案：A',
        '14. Ebbesmeyer is most famous for',
        'A. traveling widely the coastal cities of the world.',
        'B. making records for any lost objects on the sea.',
        'C. running a global currents research association.',
        'D. phoning about any doubtful objects on the sea.',
        '答案：D',
        '15. What is the purpose of the author in writing this passage?',
        'A. To call people\'s attention to ocean pollution.',
        'B. To warn people of shipping safety in the ocean.',
        'C. To explain a unique way of studying ocean currents.',
        'D. To give tips on how to search for lost objects on the beach.',
        '答案：C',
        ]
    },{
        title: `Directions: In this part there are 30 incomplete sentences. For each sentence there are four choices marked A, B, C and D. Choose the ONE answer that best completes the sentence. Then blacken the corresponding letter on the Answer Sheet.`,
        type: 2,
        arr: [
        '16.Only when he apologizes for his rudeness___________to him again.',
        'A.I will speak ',
        'B.will I speak ',
        'C.do l speak ',
        'D.I speak',
        '答案：B',
        '17. - Do you think Mom and Dad _______ late? …No, Swiss Air is usually on time.',
        'A. were ',
        'B. will be ',
        'C. would be ',
        'D. have been',
        '答案：B',
        '18. …Vm going to Venice next week. * _________. Carnival will be held then. Have fun!',
        'A. You’re crazy ',
        'B. You’re lucky ',
        'C. You’d better not ',
        'D. You never know',
        '答案：B',
        '19. Don’t defend him any more. U’s obvious that he________destroyed the fence of the garden even without apology.',
        'A. accidentally ',
        'B. carelessly ',
        'C. deliberately ',
        'D. clumsily',
        '答案：C',
        '20.In much of the animal world, night is the time_________for sleep—pure and simple,',
        'A. set aside ',
        'B. set down ',
        'C. set off ',
        'D. set up',
        '答案：A',


        '21. While intelligent people can often_______the complex, a fool is more likely to complicate the simple. ',
        'A. sacrifice ',
        'B. substitute ',
        'C. simplify ',
        'D. survive',
        '答案：C',
        '22. According to the law, all foreigners have to________with the local police within two weeks of arrival.',
        'A. associate ',
        'B. dispute ',
        'C. negotiate ',
        'D. register',
        '答案：D',
        '23. ——Would you mind answering some questions on shopping habits?______',
        'A. Yes, with great pleasure ',
        'B. No, I am afraid I can’t make it ',
        'C. Yes, it is worth the time ',
        'D. No, as long as it doesn’t take long',
        '答案：D',
        '24. As the world’s population continues to grow，the_______of food becomes more and more of a concern.',
        'A. worth ',
        'B. supply ',
        'C. package ',
        'D. List',
        '答案：B',
        '25. People complain that decisions to approve or deny a permit are often_________rather than based on fixed criteria.',
        'A. appropriate ',
        'B. conscious ',
        'C. arbitrary ',
        'D. controversial',
        '答案：C',


        '26.In much of the animal world, night is the time_________for sleep—pure and simple.',
        'A. set aside ',
        'B. set down ',
        'C. set off ',
        'D. set up',
        '答案：A',
        '27.Don’t defend him any more. It’s obvious that he_________destroyed the fence of the garden even without apology.',
        'A. accidentally ',
        'B. carelessly ',
        'C. deliberately ',
        'D. clumsily',
        '答案：C',
        '28. The manager wants to see changes in the company, and I am sure he will ______',
        'A. in particular ',
        'B. in turn ',
        'C. in charge ',
        'D. in time',
        '答案：D',
        '29. The accident caused some________to my car, but ifs nothing serious.',
        'A. harm ',
        'B.injury ',
        'C. ruin ',
        'D. damage',
        '答案：D',
        '30.I think watching TV every evening is a waste of time there are________________meaningful things to do.',
        'A. less ',
        'B. more ',
        'C. the least ',
        'D. the most',
        '答案：B',


        '31.A society cannot be successful if it throws tradition away, but it cannot be successful_________if we do something to stop progress.',
        'A. either ',
        'B. neither ',
        'C. too ',
        'D. also',
        '答案：A',
        '32. Hurry up! Mark and Carl _______ us.',
        'A. expect ',
        'B. are expecting ',
        'C. have expected ',
        'D. will expect',
        '答案：B',
        '33. When we saw the road ______ with snow, we decided to spend the holiday at home.',
        'A. block ',
        'B. to block ',
        'C. blocking ',
        'D. blocked',
        '答案：D',
        '34 If we_______ a table earlier, we couldn’t be standing here in a queue.',
        'A. have booked ',
        'B. booked ',
        'C. book ',
        'D. had booked',
        '答案：D',
        '35 John invited about 40 people to his wedding, most of_________are family members.',
        'A. them ',
        'B. that ',
        'C. which ',
        'D. whom',
        '答案：D',


        '36. The “Chinese Dream” is ______ dream to improve peopled well-being and __________ dream of harmony, peace and development.',
        'A. the; a ',
        'B. a; a ',
        'C. a; the ',
        'D. the; the',
        '答案：B',
        '37. _____everyone here, I wish you a pleasant journey back to your country.',
        'A. By means of ',
        'B. On behalf of ',
        'C. In seeu*ch of ',
        'D. For fear of',
        '答案：B',
        '38. At no time________the rules of the game. It was unfair to punish them.',
        'A. they actually broke ',
        'B. do they actually break ',
        'C. did they actually break ',
        'D. they had actually broken',
        '答案：C',
        '39. Let those in need_________that we will go all out to help them.',
        'A. to understand ',
        'B. understand ',
        'C. understanding ',
        'D. understood!',
        '答案：B',
        '40. —Do you think George has passed the driving test? —No. If so, he______his car to our college yesterday.',
        'A. would drive ',
        'B. drove ',
        'C. would have driven ',
        'D. had driven',
        '答案：C',


        '41. Mo Yan was awarded the Nobel Prize for Literature in 2012,_________ made one of the Chinese peopled long-held dreams come true.',
        'A. it ',
        'B. that ',
        'C. what ',
        'D. which',
        '答案：D',
        '42.lt ________be the vocabulary that caused you the problem in the exercise because you know a lot of words.',
        'A. may ',
        'B. couldn’t ',
        'C. should ',
        'D. needn’t',
        '答案：B',
        '43-The famous musician, as well as his students,________to perform at the opening ceremony of the 2012 Taipei Flower Expo.',
        'A. were invited ',
        'B. was invited ',
        'C. have been invited ',
        'D. has been invited',
        '答案：B',
        '44._________I have to give a speech, I get extremely nervous before I start.',
        'A.Whatever ',
        'B. Whenever ',
        'C. Whoever ',
        'D. However',
        '答案：B',
        '45.1 have an appointment___________Dr. Smith, but I need to change it.',
        'A. to ',
        'B. off ',
        'C. with ',
        'D. from',
        '答案：C',
        ]
    },{
        title: `Directions: Each of the following sentences has four underlined parts marked A, B, C and D. Identify the one that is not correct. Then blacken the corresponding letter on the Answer Sheet.`,
        type: 2,
        arr: [
        '46. He wrote a letter <em class="col-red">(that)</em> he explained <em class="col-red">(what)</em> <em class="col-red">(had happened)</em> <em class="col-red">(in)</em> the accident.',
        'AAAAA',
        'BBBBB',
        'CCCCC',
        'DDDDD',
        '答案：A',
        '47. Recycling is <em class="col-red">(one)</em> way <em class="col-red">(to protect)</em> the environment; <em class="col-red">(reusing)</em> is <em class="col-red">(the other)</em>.',
        'AAAAA',
        'BBBBB',
        'CCCCC',
        'DDDDD',
        '答案：D',
        '48.<em class="col-red">(Staying)</em> warm <em class="col-red">(at night)</em>, I would fill the woodstove, then set my alarm clock <em class="col-red">(for)</em> midnight <em class="col-red">(so)</em> I could refill it.',
        'AAAAA',
        'BBBBB',
        'CCCCC',
        'DDDDD',
        '答案：A',
        '49.At is <em class="col-red">(generally)</em> considered <em class="col-red">(unwise)</em> <em class="col-red">(to give)</em> a child <em class="col-red">(however)</em> he or she wants.',
        'AAAAA',
        'BBBBB',
        'CCCCC',
        'DDDDD',
        '答案：D',
        '50.<em class="col-red">(It)</em> is worth <em class="col-red">(considered)</em> <em class="col-red">(why)</em> the Korean drama Man from the Stars is <em class="col-red">(so)</em> popular in China. ',
        'AAAAA',
        'BBBBB',
        'CCCCC',
        'DDDDD',
        '答案：B',


        '51.The <em class="col-red">(growing speed)</em> of a plant is influenced <em class="col-red">(by)</em> <em class="col-red">(the number of)</em> factors, <em class="col-red">(most of which)</em> are beyond our control.',
        'AAAAA',
        'BBBBB',
        'CCCCC',
        'DDDDD',
        '答案：C',
        '52.<em class="col-red">(That)</em> she hadn’t kept her <em class="col-red">(mind)</em> <em class="col-red">(in)</em> her work <em class="col-red">(resulted)</em> in the failure.',
        'AAAAA',
        'BBBBB',
        'CCCCC',
        'DDDDD',
        '答案：C',
        '53.<em class="col-red">(It was)</em> in this university <em class="col-red">(where)</em> he <em class="col-red">(had studied)</em> <em class="col-red">(for)</em> seven years.',
        'AAAAA',
        'BBBBB',
        'CCCCC',
        'DDDDD',
        '答案：B',
        '54.<em class="col-red">(The director)</em> and manager <em class="col-red">(of)</em> the department <em class="col-red">(are)</em> very strict <em class="col-red">(with)</em> the employees.',
        'AAAAA',
        'BBBBB',
        'CCCCC',
        'DDDDD',
        '答案：C',
        '55.She was <em class="col-red">(angry)</em>, went <em class="col-red">(out)</em>, and <em class="col-red">(slamming)</em> the door <em class="col-red">(behind)</em> her.',
        'AAAAA',
        'BBBBB',
        'CCCCC',
        'DDDDD',
        '答案：C',
        ]
    },{
        title: `When our restaurant business failed, we headed north in a camping truck to Texas, hoping to have a “fresh start’’.
At the <em class="col-red">____56____</em> of Paio Duro Canyon (峡谷）State Park, 1 <em class="col-red">____57____</em> a job advertisement hiring
park hosts. The position offered a <em class="col-red">____58____</em> „ permanent campsite in the park, and <em class="col-red">____59____</em> , the hosts
served as a link between the park’s guests and the rangers It was the perfect solution: a
rent-free place to reorganize our lives. We entered the park and I made an <em class="col-red">____60____</em> for the following day.`,
        type: 2,
        arr: [
        '56. ',
        'A. back',
        'B. edge',
        'C. centre',
        'D. entrance',
        '答案：D',
        '57. ',
        'A. sponsored',
        'B. published',
        'C. noticed',
        'D. answered',
        '答案：C',
        '58. ',
        'A. safe',
        'B. free',
        'C convenient',
        'D. beautiful',
        '答案：B',
        '59. ',
        'A. in return',
        'B. in time',
        'C. in short',
        'D. in turn',
        '答案：A',
        '60. ',
        'A. attempt',
        'B. agreement',
        'C. appeal',
        'D. appointment',
        '答案：D',
        ]
    },{
        title: `The park was <em class="col-red">____61____</em> , so it took us some time to find an available site. That evening, as we
finished our dinner, my wife saw two large skunks walking toward our table. We <em class="col-red">____62____</em>
climbed onto the table and, for the next four hours, waited for them to <em class="col-red">____63____</em>.„ .„ our camp.
Having survived that night, we were <em class="col-red">____64____</em> that everything else would be all right. The next day we met with the people who ran the park. They explained our <em class="col-red">____65____</em> and gave us a beautiftil campsite.`,
        type: 2,
        arr: [
        '61. ',
        'A. crowded',
        'B. dangerous',
        'C. ideal',
        'D. quiet',
        '答案：A',
        '62. ',
        'A. repeatedly',
        'B. immediately',
        'C. eventually',
        'D. calmly',
        '答案：B',
        '63. ',
        'A. attack',
        'B. leave',
        'C. pass',
        'D. search',
        '答案：B',
        '64. ',
        'A. satisfied',
        'B. determined',
        'C. confident',
        'D. aware',
        '答案：C',
        '65. ',
        'A. responsibilities',
        'B. requirements',
        'C. circumstances',
        'D. conditions',
        '答案：A',
        ]
    },{
        title: `That evening, <em class="col-red">____66____</em> , we learned about the canyon <em class="col-red">____67____</em> 。They were strong and cold,
rocking our little camping truck violently, and we lay <em class="col-red">____68____</em> in the dark until the winds died away.
<em class="col-red">____69____</em> the weeks that followed, we learned to survive in our truck and <em class="col-red">____70____</em> the little money `,
        type: 2,
        arr: [
        '66. ',
        'A. moreover',
        'B. therefore',
        'C. meanwhile',
        'D. however',
        '答案：D',
        '67. ',
        'A. winds',
        'B. snows',
        'C. woods',
        'D. trails',
        '答案：A',
        '68. ',
        'A. shaking',
        'B. quarrelling',
        'C. mourning',
        'D. aching',
        '答案：A',
        '69. ',
        'A. After',
        '.B. Between',
        'C. During',
        'D. Beyond',
        '答案：C',
        '70. ',
        'A. give away',
        'B. hand out',
        'C. live on',
        'D. put aside',
        '答案：C',
        ]
    },{
        title: `my wife <em class="col-red">____71____</em> by substitute teaching. Building a successful business and then losing it had left very little time for building a successfiil <em class="col-red">____72____</em> . For a time after our business
<em class="col-red">____73____</em> I thought I might lose my family as well.
Living in the tiny <em class="col-red">____75____</em> with no television, we sat close together reading and talking. One
evening, standing under a jeweled sky, I found myself <em class="col-red">____75____</em> for all the walked the trails and climbed the canyon wails. We had become a family!`,
        type: 2,
        arr: [
        '71. ',
        'A. borrowed',
        'B. earned',
        'C. posted ^',
        'D. raised',
        '答案：B',
        '72. ',
        'A. business',
        'B. career',
        'C. family',
        'D. image',
        '答案：C',
        '73. ',
        'A. started',
        'B. failed',
        'C. expanded',
        'D. declined',
        '答案：B',
        '74. ',
        'A. truck',
        'B. park',
        'C. house',
        'D. camp',
        '答案：A',
        '75. ',
        'A. desperate',
        'B.ready',
        'C. suitable',
        'D. thankful',
        '答案：D',
        ]
    },
]