window.readingJson = [
    {
        title: ' (76)It is well-known that twins are closer to each other than most brothers and sistersafter all,they probably spend more time with each other．Parents of twins often notice than they develop special ways of communicating:they invent their own words and one car often finish the other’s sentence．In exceptional circumstances,this closeness becomes more extrecme:they invent a whole language of their own,as in the case of Grace and Virginia Kennedy from Georgia in the USA ,who communicated so successfully in their own special language than they did not speak any English at all until after they started school．\
            (77)However,these special relationships are the result if lives spent almost entirely in each other’s company．What happens when twins do not grow up together,when they are separated at birth for some reason？Are they just like any they strangers,or there still special similarities between them？professor Tom Bouchard,of the University of Minnesota,set out of find the answer to this question．He traced sixteen pairs of twins,who were adopted by different families when the were babies,and often brought up in very different circumstances．Each twin was then interviewed about every small datail of their life．\
            The results of this research make a surprising reading．Many of the twins were found to have the same hobbies,many have suffered the same point in their lives．One pair of middle-aged women’arrived for their first meeting in similar dresses,another pair were wearing similar jemellery．The most incredible similarities are to be found in the case of Jim springer and Jim lewis from ohio in the USA．The story of the’Jim Twins’made headine news across USA．Born to an immigrant woman in 1939,and adopted by different families at birth,both babies were named Jim by their new parents．\
            But what can be the explanation for these remarkable similarities？Is it all pure coincidence,or is the explanation in some way genetic？Research into the lives of twin is forcing some experts to admit that our personalities may be at least partly due to’nature’．On the other hand,analysts are also anxious to emphasise that incredible coincidences do happen all the time,not just in the lives of twins．',
        type: 2,
        arr: [
            '1,The case of Grace and Virginia Kennedy(Para．1)is to show that',
            'A,twins communicate with each other in an unusual way',
            'B,twins are more likely to suffer form speaking problems',
            'C,most twins have exceptional abilities to invent a new language',
            'D,twins won’t have an effective communication until they go to school',
            '答案：A',
            '2,The purpose of Tom Bouchard’s study is to find',
            'A,what will happen if twins spend lives entirely in the same company',
            'B,why the 16 pairs of twins have been adopted by different families',
            'C,whether separated growing up has affect on twins special similarities',
            'D,when the special similarities come into being during their growing up',
            '答案：C',
            '3,What does the word “reading”in paragraph 3 most probably mean？',
            'A,Book',
            'B,interpretation',
            'C,literature',
            'D,measurement',
            '答案：B',
            '4,According to Tom Bouchard’s resecrah ,the special similarities between twins',
            'A,depend on what the twins enjoy and suffer form',
            'B,can not be proved or accepted by all the experts',
            'C,result form the twin’s growing up and development ',
            'D,are not closely linked with where the twins are raised',
            '答案：D',
            '5,What can be learned from the last paragraph？',
            'A,Incredible coincidences happen to twins all the time ',
            'B,Nature is the only way to explain the similarities betwween twins',
            'C,The differences betwween twins are to some extent the results of genes',
            'D, similarities shows the close relationship between two strange persons ',
            '答案：C'
        ]
    }, {
        title: 'Susan was bron as the night  child in a Catholic family．(78)She sufferend form learning disabilities ever since her birth because of her mother’s poor health．\
        School as difficult for susan and she was bullied because of her different behaviours．Her siblings,who were much older,had life experiences that were unknown to their little sister．Form the time of her birth,susan was a screamer．The only really safe placethan she would use as a repeat as her bedroom ．there she would hang posters of her musical idols on the wall and sing popular musical lnto a hairbrush that he pretended was a microphone．\
        One be one the siblings moved away from home and then susan’s father died．This left her al one with an aging mother and cat．The siblings accused her mother of not expecting more out of susan．She had seen many professionals and remembered hearing the word “borderline”but didn’t know what it meant．She tried volunteer work．Her best state of mine,however,was found when she was singing and so she would regularly join others in karaoke or pubs where she could show her skills and receive appreciation from her crowd．\
        When Susan announced at Christmas that she was planning to compete in the Britains Got T\
        alent contest, her siblings tried to discourage her. It was a wonder that she was even able to do the\
        audition considering the troubles she faced just physically getting to the right place\
        The Woman I Was Born to Be"is a beautiful story written in the simple but humourous voic\
        e of the author, Susan Boyle. She tells her story from birth to the present in an interesting and educ\
        ational manner. The writing is supplemented by photos from her albums\
        I love this book! In fact, I read the whole thing in one day!\
        There is something in the stories that not only teaches the reader but also inspires us to reach\
        for our dreams-no matter how impossible they may seem to be',
        type: 2,
        arr: [
            '6. This passage should be',
            'A. a news report',
            'B. a biography',
            'C. a book review',
            'D. an introduction',
            '答案：C',
            '7. When Susan was young',
            'A. her mother died ofan illness',
            'B. her siblings liked her very much',
            'C. she was fond of music',
            'D. she was envied at school',
            '答案：C',
            '8. According to the passage, which was NOT true？',
            'A. susan‘s mother expected too much out of her',
            'B. Susan tried doing a lot of volunteer work',
            'C. Susans siblings tried to stop her from competing in the Britains Got Talent contest.',
            'D. susan‘s performances were well received by the customers in pubs',
            '答案：A',
            '9. The book"The Woman I Was Born to Be"',
            'A. is always a best-seller',
            'B. is written in a serious voice',
            'C. is full of sad stories',
            'D contains some photos of Susan',
            '答案：D',
            '10. What does the author think of Susan Boyle?',
            'A. Pitiful and selfless',
            'B. Shy and passive',
            'C Great and generous',
            'D Determined and inspiring',
            '答案：D',
        ]
    }, {
        title: `Questions I1 to 15 are based on the following passage.
        (79)To build an incredible and successful relationship is something like erecting a building. P
        irst of all, you should start with an idea which is expected by everyone, and then you can put a soli
        d foundation stone for that idea. Putting a strong foundation stone is very important and it keeps y
        our building steady. Every part of that building is totally depending uponthat solid foundation
        So, here are the three rules to establish a successfil relationship
        The first rule is just having fun. Once relationship is established then the things become stab!
        e. Once it gets stable then you start feeling stifled(
        ))and fun is no longer there in your relationship. But remember this thing is very dangerous for r
        elationship. You can plan something great like a weekend road trip. Even you can also plan some o
        your favorite activities at least twice a month. Enjoy laughing with each other and try to find diff
        erent ways to keep this laughter alive
        The second rule is
        In relationship it is important that both the partners should de
        serve equal treatment. If anyone of the Partners dominates to the other then such relationship is sur
        ly not going to survive for a long time. Such relationships are called unbalanced relationship and
        it is going to give lots of pain. So, try to give respect to each other equally
        The third rule is always to be open and honest with
        each other. Another good and important p
        art of any relationship is being honest and open-minded with your partner. Whenever the problem
        arises in your relations, honesty is very crucial. Even being open-minded with each other is a foun
        dation to your good relationship. Honesty is most valuable thing. If you become very honest with
        each other then problems can be very easily sorted out.
        You need put lots of efforts to build a successful relationship. This effort is required from bot
        h the partners And the reward which you are going to get will be fantastic. (80)If the three rules m
        entioned above are maintained very well then there will be a strong chance of long term and wond
        erful relationship`,
        type: 2,
        arr: [
            '11. What is the best title for this passage?',
            'A. Good Relationship and Success',
            'B How to Build a Successful Relationship',
            'C Solid Foundation and Building Relationship',
            'D. The Benefits from Good Relationship',
            '答案：B',
            '12. In the first paragraph the author mainly wants to tell us',
            'A. the concept of good relationship',
            'B the importance of good relationship',
            'C the characteristics of good relationship',
            'D. what is the most important thing in building good relationship',
            '答案：D',
            '13. what‘s the second rule?',
            'A. Giving respect to each other equall',
            'B. Being generous to friends',
            'C. Giving timely help to friends',
            'D. Treating friends eauall‘',
            '答案：A',
            '14. The underlined word"crucial" in the fifth paragraph probably means',
            'A. critic',
            'B,enough',
            'C. sufficient',
            'D. efficient',
            '答案：A',
            '15. It can be learned from the last paragraph that',
            'A. it is not difficult to build a good relationship',
            'B one can benefit a lot from a wonderful relationship',
            'C honesty helps approaching problems',
            'D. being open-minded is a basis to build a good relationship',
            '答案：B',

        ]
    }, {
        title: `Directions: In this part there are 30 incomplete sentences. For each sentence there are four choices marked B, C and D. Choose the ONE answer that best completes the sentence. Then blacken the corresponding letter on the. Answer Sheet`,
        type: 2,
        arr: [
            '16. With inspiration from other food cultures, Amcrican food culture can take a ________ for the better',
            'A. share',
            'B, chance',
            'C, turn',
            'D, lead',
            '答案：C',
            '17. I am always delighted when I receive an e-mail from you. ________the party on July Ist, I shall be pleased to attend.',
            'A. On account of',
            'B. In response to',
            'C, In view of',
            'D, With regard to',
            '答案：D',
            '18 f you are in trouble, Mike is always willing to________a hand',
            'A, lend',
            'B, shake',
            'C, wave',
            'D, wa',
            '答案：A',
            '19. While she was in Paris, she developed a________for fine art',
            'A, way',
            'B, relation',
            'C, taste',
            'D, habit',
            '答案：C',
            '20. Before you pay a visit to a place of interest, look in your local library________a book about it',
            'A,on',
            'B. at',
            'C,for',
            'D,to',
            '答案：C',


            '21. -How far can you run without stopping  ________,I’ve never tried',
            'A, Dont mention it',
            'B. Thats all right',
            'C, I have no idea',
            'D. Go ahead',
            '答案：C',
            '22. The president of the World Bank says he has a passion for China, ________he remembers starting as early as his childhood',
            'A, where',
            'B, which',
            'C, what',
            'D. when',
            '答案：B',
            '23.-Could I use your car tomorrow morning -Sure,I ________ a report at home',
            'A, will be writing',
            'B, will have written',
            'C, have written',
            'D, have been writing',
            '答案：A',
            '24. Not until he went through real hardship ________the love we have for our families is important',
            'A. had he realized',
            'B, did he realize',
            'C. he realized',
            'D. he had realized',
            '答案：B',
            '25. I expect our English teacher will be back this weekend, ________?',
            'A. won’t she',
            'B. will she',
            'C,do I',
            'D. don’t I',
            '答案：A',


            '26. You cannot accept an opinion ________to you unlessit is based on facts',
            'A, offering',
            'B, to offer',
            'C, having offered',
            'D. offered',
            '答案：D',
            '27. You must learn to consult your feelings and your reason ________ you reach any decision.',
            'A. although',
            'B, before',
            'C, because',
            'D, unless',
            '答案：B',
            '28,At our factory there are a few machines similar to ________  described in this magazine',
            'A, them',
            'B. these',
            'C, those',
            'D, ones',
            '答案：C',
            '29, ________  at the photos, illustrations, title and headings and you can guess what the reading is about',
            'A,To look',
            'B, Looking',
            'C, Having looked',
            'D, Look',
            '答案：D',
            '30.It was ________  cold winter night and the moon was shining brightly across  night sky',
            'A./,a',
            'B a, the',
            'C. the,a',
            'D. the, /',
            '答案：B',


            '31. The watch was very good, and he  ________ 20 percent down for it',
            'A. paid',
            'B. cost',
            'C. bought',
            'D. spent',
            '答案：A',
            '32.I  ________ to my cousin’s birthday party last night, but I was not available',
            'A. went',
            'B, had gone',
            'C, would go',
            'D. would have gone',
            '答案：D',
            '33. -Do you think Mom and Dad  ________ late? -No, Swiss Air is usually on time',
            'A,were',
            'B, will be',
            'C, would be',
            'D, have been',
            '答案：B',
            '34.There is no simple answer,  ________ is often the case in science',
            'A,as',
            'B, that',
            'C, when',
            'D. whe',
            '答案：A',
            '35. I have heard a lot of good things about you  ________ I came back from abroad',
            'A. since',
            'B. until',
            'C. before',
            'D. when',
            '答案：A',


            '36. Since nobody gave him any help, he ________  have done the research on his own',
            'A. can',
            'B. must',
            'C. would',
            'D. need',
            '答案：B',
            '37. Eye doctors recommend that a childs first eye exam  ________ at the age of six months old',
            'A, was',
            'B,  be',
            'C. were',
            'D,  is',
            '答案：B',
            '38. Team leaders must ensure that all members ________  their natural desire to avoid the embarrasment associated with making mistakes',
            'A. get over',
            'B, look over',
            'C, take over',
            'D. come over',
            '答案：A',
            '39. The Forbidden City attracts a  ________ stream of visitors every day, especially during nationa holidays.',
            'A, constant',
            'B, Main ',
            'C, powerful  ',
            'D, shallow',
            '答案：A',
            '40. It,s said that the power plant is now  ________ large as what it was',
            'A, twice as',
            'B. as twice',
            'C. twice much',
            'D. much twice',
            '答案：A',


            '41 ----I’m looking for a nearby place for my holiday. Any good ideas.? How about the Moon Lake? It is ________ easy reach of the city',
            'A, by',
            'B, beyond',
            'C, within',
            'D, from',
            '答案：C',
            '42. My father has many books, but he has  ________ English books',
            'A. little',
            'B. a little',
            'C. few',
            'D, a few ',
            '答案：C',
            '43. Traditionally, college students hold a graduation ceremony to encourage themselves before they ________  on their life joumey',
            'A give up',
            'B, settle down',
            'C, get through',
            'D, set off',
            '答案：D',
            '44. old-fashioned phones matter when wireless networks  ________ in disasters.',
            'A. turn down',
            'B, turn out',
            'C, break down',
            'D. break out',
            '答案：C',
            '45,  ________ small, the company has about 1,000 buyers in over 30 countries',
            'A, As',
            'B, If',
            'C. Although',
            'D. Once',
            '答案：C',
        ]
    }, {
        title: `Directions: Each of the following sentences has four underlined parts marked A. B, C and D,Identify the one that is not correct Then blacken the corresponding letter on the Answer Sheet`,
        type: 2,
        arr: [
            '46. If (asking) to look after luggage for( someone) else, (inform) the police (at once)',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：A',
            '47. It may not be a (great )suggestion. But before (a good one) is( put) forward, well  make do( with) it',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：B',
            '48. The book tells stories( of) the earthquake( through) the eyes of those (which) lives were (affected)',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '49,The project requires (close) (teamwork). (Something )will be achieved unless we work (well) together',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '50. ( Among) the crises that( face) humans (are) the( lack) of natural resources',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '51. I stopped the car (taking) ( a short break) (as) I was feeling( tired)',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：A',
            '52.A (serious) study of( physics) is impossible (with) some( knowledge )of mathematics',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
            '53. Every day( reading )a proverb (aloud) several times( until) you have it (memorized)',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：A',
            '54. It’s( an) either-or situation-we can buy a new car this year( or) we can (go on )holiday but we (cant another)',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：D',
            '55 Onc can always manage (to do) (more) things, no matter (what) full ones schedule is (in) life   ',
            'AAAAA',
            'BBBBB',
            'CCCCC',
            'DDDDD',
            '答案：C',
        ]
    }, {
        title: `The first time I saw Suzy Khan, I knew I had to help her. She was really small for her age of 12. The boy in my class often<em class="col-red">___56___</em> about her and laughed their heads off. She would open a book, pretending to read, with tears dropping on the open page.
All I knew was that she was an orphan(孤儿)from Africa. She had just been adopted by a family in town who <em class="col-red">___57___</em> that the best way for her to learn American ways of life was to be with american kids. I looked down at this _<em class="col-red">___58___</em> girl and promised myself that someh would help her.
But how could I help her <em class="col-red">___59___</em> in with us? There had to be a <em class="col-red">___60___</em> .  `,
        type: 2,
        arr: [
            '56. ',
            'A. joked',
            'B. cared',
            'C. trains',
            'D. worried',
            '答案：A',
            '57. ',
            'A. reported',
            'B. decided',
            'C complained',
            'D. questioned',
            '答案：B',
            '58.',
            'A. rich',
            'B,proud',
            'C. tiny',
            'D,popular',
            '答案：C',
            '59.',
            'A. come',
            'B, fall ',
            'C,fit  ',
            'D,tie',
            '答案：C',
            '60,',
            'A,manner ',
            'B. pattern  ',
            'C,choice',
            'D way',
            '答案：D',
        ]
    }, {
        title: `One day, when I went into the classroom, I saw that Suzy had <em class="col-red">___61___</em>  her geography book to a picture of a train, and in her notebook, she had made a(n) <em class="col-red">___62___</em> copy.
I was surprised and thought that she could do something in the coming  <em class="col-red">___63___</em> Show,so, I took her to see the art teacher, Miss Parker, and showed her what Suzy had <em class="col-red">___64___</em> ."why, it‘s wonderful, "said Miss Parker, who then showed us a poster she had painted <em class="col-red">___65___</em>  the talent show.`,
        type: 2,
        arr: [
            '61. ',
            'A. read',
            'B. taken',
            'C. opened',
            'D,put',
            '答案：C',
            '62. ',
            'A. free',
            'B. perfect',
            'C. final',
            'D. extra',
            '答案：B',
            '63. ',
            'A are',
            'B talk',
            'C quiz',
            'D. talent',
            '答案：D',
            '64. ',
            'A. colored',
            'B. written',
            'C. carved',
            'D. drawn',
            '答案：D',
            '65.',
            'A. at',
            'B. after',
            'C. for ',
            'D. around',
            '答案：C',
        ]
    }, {
        title: ` "I need more of these, but I just don t have enough
<em class="col-red">___66___</em>  Could you help me, Suzy?
On the day of the talent show, suzy‘s <em class="col-red">___67___</em>  were everywhere---all over the hall and all over the school, each one different.
And finally, "said Mr Brown, the schoolmaster, at the end of the show, "we have a (n) <em class="col-red">___68___</em>  award. I‘m sure you’ve all noticed the wonderful posters. Everyone nodded. " One of our own students <em class="col-red">___69___</em> them”
I could hear everyone whispering. Who in our school could draw <em class="col-red">___70___</em>  . `,
        type: 2,
        arr: [
            '66.',
            'A. room ',
            'B, time ',
            'C, paper ',
            'D,interest',
            '答案：B',
            '67. ',
            'A. gifts',
            'B, books',
            'C. photos',
            'D. posters',
            '答案：D',
            '68.',
            'A. special',
            'B, academic',
            'C. national',
            'D. rayal',
            '答案：A',
            '69. ',
            'A painted',
            'B. found',
            'C. printed',
            'D. collected',
            '答案：A',
            '70.',
            'A. very',
            'B. that',
            'C quite',
            'D. too',
            '答案：B',
        ]
    }, {
        title: `well ?"
Mr. Brown waited a while before saying,”<em class="col-red">___71___</em>   this student worked so hard on the
posters, she deserves a _<em class="col-red">___72___</em> ,too. Our mystery(神秘)artist is our new student -.Suzy
Khan!”
Mr. Brown thanked her for all the wonderful posters and gave her a professional artist‘s set”Thank you,” she cried.
I <em class="col-red">___73___</em>  ,at that time when I was looking at her excited face, she’d probably never <em class="col-red">___74___</em>  anything in her whole life.
Everyone, started to<em class="col-red">___75___</em>  their hands. Suzy Khan gave them a shy smile and the
applause was defening. I knew then Suzy was going to ne all right`,
        type: 2,
        arr: [
            '71.',
            'A.If',
            'B. Though',
            'C. Unless',
            'D. Since',
            '答案：D',
            '72.',
            'A. prize',
            'B. rank',
            'C. rest',
            'D,place',
            '答案：A',
            '73,',
            'A,replied ',
            'B. realized',
            'C, remembered',
            'D, regretted',
            '答案：B',
            '74. ',
            'A. offered',
            'B,valued',
            'C owned',
            'D. controlled',
            '答案：C',
            '75. ',
            'A. clap',
            'B. wave',
            'C. raise',
            'D. shake',
            '答案：A'
        ]
    },
]