window.transformJson = [
    "(76)It is well-known that twins are closer to each other than most brothers and sistersafter all,they probably spend more time with each other．",
    "76. 众所周知，双胞胎比大多数兄弟姐妹更亲密，毕竟他们可能会花更多的时间在一起。",
    "(77)However,these special relationships are the result if lives spent almost entirely in each other’s company．",
    "77.但是这一特殊的关系是他们几乎全部时间都互相陪伴的结果。",
    "(78)She sufferend form learning disabilities ever since her birth because of her mother’s poor health．",
    "78.她因母亲身体不好，自出生以来就患有学习障碍。",
    "79)To build an incredible and successful relationship is something like erecting a building. ",
    "79.建立一个令人难以置信并成功的关系就像建立一座大厦。",
    " (80)If the three rules m entioned above are maintained very well then there will be a strong chance of long term and wond erful relationship",
    "80.如果上述三条规则保持得很好，那么就会有建立长期友好关系的机会。",
    "81.你最好乘坐出租车去电影节的开幕式，不然就要迟到了",
    "81. You'd better take a taxi to the opening ceremony of the movie festival, or you will be late.",
    "82.普遍认为在公共场合大声说话是粗鲁的，应该避免",
    "82. It is generally believed that speaking loudly in public is rude and should be avoided.",
    "83.你看上去很疲惫，为什么不回家好好睡一觉呢",
    "83. You look tired. Why don't you go home and have a good sleep?",
    "84.看，十年前种的那棵树现在长得多高了啊",
    "84. Look, how tall the tree planted ten years ago is.",
    "85.学生们逐渐认识到友谊胜过金钱，患难朋友才是真朋友",
    "85. Students gradually realize that friendship is better than money, and that friends in need are friends indeed.",




    '76. Not only do we lessen our carbon dioxide emissions, but we also get a good exercise out o fit.',
    '我们不仅减少二氧化碳的排放，而且还可以得到良好的锻炼。',
    '77. But you can do your own variation any time just always prioritize how you can use less en ergy and produce even lesser trash and pollution.',
    '但你可以随时自己调整，只需要优先考虑如何使用较少的能量和产生更少的垃圾和污染。',
    '78. At this point, no one had called to claim the dog, so Ann decided to keep it.',
    '这时，没有人打电话认领狗，所以安决定收养它。',
    '79. Movie theaters were one of the few places you could sit all day and—most important sit in air conditioning.',
    '电影院是你能坐一整天的地方之一，最重要的是，还有空调。',
    '80. But we returned the next day and saw the same two movies again, twice more.',
    '但是我们第二天又回来了，再次看了相同的两部电影，并且是两次。',
    '81. 考官将会问你几个关于科技发展的问题。',
    'The examiners will ask you some questions about the development of science and technology.',
    '82. 他在英语学习方面取得了比其他同学更大的进步。',
    'He has made greater progress in English learning than other students.',
    '83. 就你的观点，缺少均衡饮食以及室外运动会有怎样的负面结果？',
    'From your point of view, what is the negative result of lack of balanced diet and outdoor sports?',
    '84. 我希望尽快收到你的照片。',
    'I hope to get your picture as soon as possible.',
    '85. 不管天有多晚，他从不把今天的事情拖到明天。',
    'No matter how late it is, he never puts off today\'s things till tomorrow.',


    '76.Strangely enough, after the trial, the Ashleys asked Mumbet to come back and work for them as a paid employee.',
    '奇怪的是，庭审结束后Ashley一家人让Mumbet回来，作为有偿雇员为他们工作。',
    '77.An electric toothbrush senses how long and how well you brushy and it lets you track yourperformance on your phone.',
    '电动牙刷能感觉到你刷了多长时间，刷的干不干净，并且你可以在手机上跟踪你的表现。',
    '78. The company says the Kolibree will go on sale this summer, for $99 to $199, developing on features.',
    '该公司表示，基于这个特点Kolibree将在今年夏天上市销售，售价为99美元至199美元。',
    '79. Amazed that he remembered this long and difficult piece of music and played it perfectly, his teachers say Samuel is unbelievable.',
    '惊讶的是，他想起了这首又长又难的曲子，并且演奏得很完美，他的老师们说塞缪尔令人难以置信。',
    '80. His family says that even when he was a young boy3 Samuel heard someone read a stor>; and then he could retell the story word for word,',
    '他的家人说，即使在他还是个小男孩的时候，塞缪尔听到有人读了一个故事，然后他就能一字不差地复述这个故事。',
    '81. 现在，很多年青人热衷于在网上征求游伴。',
    'Now, many young people are keen to seek travel partner on the Internet.',
    '82. 起先观众们听不清台词，但最终还是被演员们的表演打动了。',
    'At first, the audience could not hear the lines clearly, but in the end they were moved by the actors\' performances.',
    '83. 玛丽在报纸上了解到相关信息，这才意识到粮食浪费的问题有多严重。',
    'Marie learned relevant information in newspapers, which realized how serious the problem of food waste is.',
    '84. 充分利用时间并不意味着从早到晚不停地看书。',
    'Making full use of time does not mean reading books from morning till night.',
    '85. 到目前为止，我们学过的英语单词总计大约有2000个。',
    'So far, we have learned about 2000 English words.',

    '第四部分缺失-------------------',
    '第四部分缺失-------------------',

    '76.When l was a child, my parents gave me a piggy bank to teach me that, if I wanted something, I should save money to buy it.',
    '当我还是个孩子的时候，我父母给了我一个储蓄罐来教我，如果我想要什么，我应该存钱买它。',
    '77,Originally you had to break the bank to get to the money, bringing in a sense of seriousness into savings.',
    '最初，你不得不去银行取钱，给储蓄带来一种严肃的感觉。',
    '78. Amazon is building three glass spheres filled with trees, so that employees can "work and socialize in a more natural, park-like setting. ^',
    '亚马逊正在建造三个装满树木的玻璃球，这样员工就可以在一个更自然的、公园般的环境中工作和社交。',
    '79. A city child5s summer is spent in the street in front of his home, and all through the long summer vacations I sat on the edge of the street and watched enviously th^ other boys on the block play baseball,',
    '一个城市孩子的暑假是在他家前面的街上度过的，而在这个漫长的暑假里，我坐在马路边羡慕地看着其他男孩打棒球。',
    '80.Since I was much alone I had become an enthusiastic reader and I had gone through the books-for-boys- series,',
    '因为我很孤独，所以我成了一个热心的读者，我读过《男孩系列》的书。',
    '81. 我认为如果不是很急，你不必乘坐出租车出行。',
    'I think if it\'s not urgent, you don\'t need to take a taxi.',
    '82. 经过十年的努力，他终于实现了自己的梦想。',
    'After ten years of hard work, he finally realized his dream.',
    '83. 他好像什么都知道了。',
    ' He seems to know everything.',
    '84. 如果方便的话，请帮我从邮局取回包裹。',
    'If you are convenient, please help me pick up the package from the post office.',
    '85. 今天下午我没空，我和牙医有约。',
    'I\'m not free this afternoon. I have an appointment with a dentist.',


    '76.The National Trust in Britain plays an increasingly important part m the preservation forpubiic enjoyment of the best that is left unspoiled of the British countryside,',
    '英国国家信托在维护公众享有最好的原始英国乡村方面发挥着越来越重要的作用。',
    '77.Why do we form an opinion about someone without really knowing anything about him or her ™ aside perhaps from a few remarks or readily observable traits.',
    '为什么我们会对有些人产生看法——也许除了几句话或容易观察到的特征外，就一无所知了。',
    '78.Howver, if we resist initial stereotypical impressions, we have a chance to be aware of what a person is truly like. .',
    '然而，如果我们抵制最初的刻板印象，我们就有机会了解一个人真正的样子。',
    '79.Some researchers conclude that differences in intelligence result from ditFerenc^s in the speed and effectiveness of information processing by the brain.',
    '一些研究人员得出结论，智力的差异是由于大脑信息处理速度和效率的不同造成的。',
    '80.Gardner believes that the purpose of school should be to encourage development of all of our intelligences.',
    '加德纳认为学校的宗旨应该是鼓励发展我们所有的智能。',
    '81.众所周知，成功来自勤奋，不努力则一事无成。',
    'As we all know, success comes from diligence, and without effort nothing is achieved.',
    '82.这款手机式样新颖、携带方便，深受年轻人的欢迎。',
    'This mobile phone is fashionable and portable, and is popular among young people.',
    '83.只要专心学习，你一定能顺利通过考试。',
    'If you concentrate on your studies, you will pass the exam successfully.',
    '84.第一次写英语作文时，犯了许多拼写错误.',
    'When I first wrote my English composition, I made a lot of spelling mistakes.',
    '85.这个游戏的规则太复杂，三言两语解释不清。',
    'The rules of the game are too complicated to explain in two words or three.',
]