window.transformJson = [
    "26.This is the worst hospital I have ever seen. ",
    "答案：这是我见过的最差的医院。",
    "27.What would you like to drink, mineral water or tea?",
    "答案：你喜欢喝点什么，矿泉水还是茶水？",
    "28.It is known to all that exercises are good for health.",
    "答案：众所周知，锻炼有益于健康。",
    "29.The traffic jams during morning and afternoon rush hours are a headache in big cities now.",
    "答案：上下班高峰期的交通拥挤问题是大城市目前的一个棘手问题。",
    "30.You needn’t go there anymore. He already knows about it.",
    "答案：你不必去了，他已经知道那件事了。",
    "31.What kind of life do most people enjoy?",
    "答案：多数人喜欢什么样的生活？",
    "26.It is well known that coal is an important source of energy.",
    "答案：众所周知，煤炭是重要的能源。",
    "27.It was a hard job, but he did not mind.",
    "答案：这项工作很艰苦，但他并不在乎。",
    "28.He is the only Chinese who has ever won the award.",
    "答案：他是唯一获得过这个荣誉的中国人。",
    "29.Bill hit his car into a wall last night.",
    "答案：昨晚比尔开车时车撞到了墙上。",
    "30.People all over the world are trying to help the people in the quake-stricken areas.",
    "答案：全世界人民都在尽力帮助遭受地震地区的人民。",
    "31.Both Ann and Mary are suitable for the job.",
    "答案：安妮和玛丽都适合干这项工作。",
    "26.The best time to read English is in the morning.",
    "答案：朗读英语的最佳时间是在早晨。",
    "27.It takes a lot of time to learn a foreign language.",
    "答案：学习一门外语需要很多时间。",
    "28.Jane moved to New York at the end of last month.",
    "答案：简在上月底就移居纽约了。",
    "29.Fred was such a hardworking student that he soon came out first in the class. ",
    "答案：弗瑞德是一个学习十分用功的学生，所以不久他就成了班里学习最好的学生。",
    "31.Are you fond of music?",
    "答案：你喜欢音乐吗？",
    "27.This one’s pretty, but it costs too much.",
    "答案：这个很漂亮，但是很贵。",
    "28.It has not been decided yet whether they will take part in our experiment.",
    "答案：他们是否参加我们的试验还没有决定。",
    "30.I knocked on his door but nobody came to answer it.",
    "答案：我敲了他的门，但没人来开门。",
    "27.Don’t believe whatever he tells you.",
    "答案：无论他告诉你什么都不要相信。",
    "28.Not all Americans are interested in sports, of course.",
    "答案：当然，并非所有美国人都对运动赶兴趣。",
    "29.It normally takes a semester for a college freshman to adjust to his college life.",
    "答案：大学新生一般需要花一个学期来适应大学生活。",
    "27.My idea is that this experiment should be stopped.",
    "答案：我的意见是这个实验应该停止。",
    "28.I’ll have to try using the search engines.",
    "答案：我得试着用这个搜索引擎。",
    "30.The People’s Republic of China (PRC), founded on October 1, 1949, covers an area of 9.6 million square kilometers.",
    "答案：中华人民共和国成立于1949年10月1日，国土面积约960万平方公里。",
    "31.A lot of natural resources in the mountain area will be exploited and used.",
    "答案：那个山区有许多自然资源有待于开发利用。",
    "26.These goods are not up to standard.",
    "答案：这些商品未达到标准。",
    "28.We have made little progress.",
    "答案：我们没有取得什么进展。",
    "31.My classmate is much cleverer than I.",
    "答案：我的同学比我聪明多了。",
    "26.I don’t know who broke the window.",
    "答案：我不知道谁打破了窗户。",
    "27.The girls are busy making preparations for the weekend party.",
    "答案：姑娘们忙着准备周末的晚会。",
    "28.About half of the fruit is ripe.",
    "答案：大约有一半的水果已经成熟了。",
    "29.Most students feel satisfied with the progress they’ve made.",
    "答案：大多数学生对自己所取得的进步感到满意。",
    "28.Let’s try something different.",
    "答案：让我们尝尝其它不同的口味。",
    "29.A friend of mine from high school is working in England now.",
    "答案：我高中的一个朋友目前在英格兰工作。",
    "30.Could you tell me where the post office is?",
    "答案：请问邮局在哪里？",
    "31.He has a foreign friend who lives in the United States.",
    "答案：他有一个住在美国的外国朋友。",
    "29.I was having a nap when suddenly the telephone rang.",
    "答案：我在睡觉时，电话铃突然响了。"
]