window.xuanzetiJson = [
    "1.-Could I borrow your car, please?",
    "-______________________",
    "A.Good idea.",
    "B.No hurry.",
    "C.With pleasure.",
    "D.No surprise.",
    "答案：C",
    "1.- I'm going to Beijing next week, you know it's one of the most beautiful cities in China.",
    "- _____________________",
    "A.Enjoy yourself",
    "B.It's a pleasure",
    "C.Good luck",
    "D.very good",
    "答案：A",
    "3.- Do you mind my smoking here?",
    "- _______ ",
    "A.No, thanks.",
    "B.Yes, I do.",
    "C.Yes. I'd rather not.",
    "D.Good idea.",
    "答案：B",
    "3.- Thank you for your invitation.",
    "- _________ ",
    "A.It doesn't matter.",
    "B.It's a pleasure.",
    "C.It's a small thing.",
    "D.I'll appreciate it.",
    "答案：B",
    "4.- Good morning, John. How are you doing?",
    "- _________ ",
    "A.I'm pleased.",
    "B.Good night.",
    "C.Not so bad. And you?",
    "D.How do you do?",
    "答案：C",
    "1.- How much is that meat, please?",
    "- _____________________",
    "A.Ten o'clock.",
    "B.Ten yuan a kilo.",
    "C.I like it very much.",
    "D.I don't like.",
    "答案：B",
    "3.- Hi, Tom, how's everything with you? ",
    "- ___________, and how are you?",
    "A.Don't mention it",
    "B.Hm, not too bad",
    "C.Thanks",
    "D.Pretty fast",
    "答案：B",
    "4.- Could I borrow your car for a few days?",
    "- ________  ",
    "A.Yes, you may borrow.",
    "B.Yes, go on.",
    "C.Sure, here is the key. Enjoy your journey.",
    "D.It doesn't matter.",
    "答案：C",
    "5.- Excuse me, how much is the jacket? ",
    "- It's 499 Yuan. ________",
    "A.Oh, no. That's OK!",
    "B.How do you like it?",
    "C.Which do you prefer?",
    "D.Would you like to try it on?",
    "答案：D",
    "1.- What do you do on Sunday?",
    "- _______",
    "A.I 'm a teacher.     ",
    "B.I play football.    ",
    "C.You are a student.   ",
    "D.They clean rooms.  ",
    "答案：B",
    "3.- What do you think of this novel?",
    "- _________ ",
    "A.I've read it.",
    "B.It's well-written.",
    "C.It was written by my uncle.",
    "D.I bought it yesterday.",
    "答案：B",
    "1.- Excuse me, when will the 17:15 train arrive? ",
    "- _________",
    "A.I don't tell you.",
    "B.It's been delayed one hour.",
    "C.You have to be patient.",
    "D.Don't ask me.",
    "答案：B",
    "2.- Let's go to the library this afternoon.",
    "- _________",
    "A.Yes, that's right.",
    "B.No. I can't.",
    "C.What about you?",
    "D.That's a good idea.",
    "答案：D",
    "4.- It's rather cold in here. Do you mind if I close the window?",
    "- ________ ",
    "A.Yes, please.",
    "B.No, please.",
    "C.Sure, please.",
    "D.I don't like it.",
    "答案：B",
    "1.- Shall we sit up here on the grass or down there near the water?",
    "- _____",
    "A.I'd rather stay here if you don't mind.",
    "B.Sorry, I don't like neither.",
    "C.Certainly, why not？",
    "D.Yes, we like these two places.",
    "答案：A",
    "3.- How much is this necklace?",
    "- _________ ",
    "A.It's very nice.",
    "B.It's a birthday present from my parents.",
    "C.It costs fifty pounds.",
    "D.It's a bargain.",
    "答案：C",
    "4.- Thank you for calling.",
    "- _________ ",
    "A.Don't mention it.",
    "B.That's fine.",
    "C.Nice talking to you.",
    "D.Call back again.",
    "答案：C",
    "1.- Excuse me, but can you tell me the way to the post office？",
    "- _____",
    "A.Don't ask that.",
    "B.Sorry, I'm a stranger here.",
    "C.No, I can't say that.",
    "D.No, you're driving too fast.",
    "答案：B",
    "2.- Are you going on holiday for a long time?",
    "- _________ ",
    "A.It was a long time.",
    "B.Two weeks ago.",
    "C.No. Only a couple of days.",
    "D.Not long time ago.",
    "答案：C",
    "4.- Good morning, may I speak to Mark, please?",
    "- _________ ",
    "A.Who's there?",
    "B.Who's that speaking?",
    "C.Who are you?",
    "D.Who wants to speak to Mark?",
    "答案：B",
    "5.- Is it possible for you to work late tonight?     ",
    "- _______ ",
    "A.I like it.",
    "B.I'll do that.",
    "C.I'd love to.",
    "D.I think so.",
    "答案：D",
    "1.- Thank you very much for giving me so much help. ",
    "- _____________________.",
    "A.No thank you",
    "B.You're welcome",
    "C.OK",
    "D.Thanks",
    "答案：B",
    "2.- Could you help me with my physics, please？",
    "- ________ ",
    "A.No, no way.",
    "B.No, I couldn't.",
    "C.No, I can't.",
    "D.Sorry I can't. I have to go to a meeting right now.",
    "答案：D",
    "3.- Congratulations! You won the first prize in today's speech contest.",
    "- ________ ",
    "A.Yes, I beat the others.",
    "B.No, no, I didn't do it well.",
    "C.Thank you.",
    "D.It's a pleasure.",
    "答案：C",
    "4.- How are you, Bob? ",
    "- ________",
    "A.How are you?",
    "B.I'm fine. Thank you.",
    "C.How do you do?",
    "D.Nice to meet you.",
    "答案：B",
    "1.- I believe we've met somewhere before.",
    "- No, ____________________. ",
    "A.it isn't the same",
    "B.it can't be right",
    "C.I don't think so",
    "D.I'd rather not",
    "答案：C",
    "2.- What's the problem with your bike?",
    "- _________ ",
    "A.Not at all.",
    "B.Good, thank you.",
    "C.Nothing serious.",
    "D.Sure",
    "答案：C",
    "3.- How's your family?",
    "- _________ ",
    "A.Thanks all the same.",
    "B.Thanks for calling.",
    "C.Not too bad.",
    "D.Don't mention it.",
    "答案：C",
    "4.- What does Tom's wife do for a living?",
    "- _________",
    "A.She is a doctor.",
    "B.Tom loves his wife.",
    "C.She has a happy life.",
    "D.She lives far from here.",
    "答案：A",
    "5.- Wow! This is a marvelous room! I've never known you're so artistic.",
    "- ______ ",
    "A.Great, I am very art-conscious.",
    "B.Don't mention it.",
    "C.Thanks for your compliments.",
    "D.It's fine.",
    "答案：C"
]

window.understanding = [{
    title: '词汇与语法',
    type: 2,
    arr: [
        "16.The news made the old lady very ______.",
        "A.sadder     ",
        "B.sad     ",
        "C.sadly     ",
        "D.sadness",
        "答案：A",
        "17.A number of people _____at the street corner.",
        "A.am",
        "B.is",
        "C.are",
        "D.be",
        "答案：C",
        "18.Measles(麻疹) ________ a long time to get over.",
        "A.spend",
        "B.spends",
        "C.take",
        "D.takes",
        "答案：D",
        "19.Tom ________ more than twenty pounds on the novel.",
        "A.spent",
        "B.paid",
        "C.cost",
        "D.took",
        "答案：A",
        "20.Eggs, though rich in nourishments, have ______ of fat.",
        "A.a large number",
        "B.the large number",
        "C.a large amount",
        "D.the large amount",
        "答案：C",
        "16.At the _______ of the police, those people ran off in all directions.",
        "A.sight         ",
        "B.look              ",
        "C.watch             ",
        "D.view",
        "答案：A",
        "17.You’d better wear more clothes. It’s _____cold today.",
        "A.much too",
        "B.too much",
        "C.very much",
        "D.much very",
        "答案：A",
        "18.I don’t know _______ to deal with such matter.",
        "A.what",
        "B.how",
        "C.which",
        "D./",
        "答案：B",
        "19.You had better ________ a doctor as soon as possible.",
        "A.seeing",
        "B.saw",
        "C.see",
        "D.seen",
        "答案：C",
        "16.The accident was ______ to careless driving.",
        "A.for     ",
        "B.likely     ",
        "C.due     ",
        "D.because",
        "答案：C",
        "17.“I think it will be fine tomorrow.“,“Oh, I hope _______.“",
        "A.not          ",
        "B.it be           ",
        "C.so             ",
        "D.it does          ",
        "答案：C",
        "18.The boy is not happy at the new school. He has ________ friends there.",
        "A.few",
        "B.a few",
        "C.little",
        "D.a little",
        "答案：A",
        "19.When Lily came home at 5 p.m. yesterday, her mother _____dinner in the kitchen.",
        "A.cooked",
        "B.was cooking",
        "C.cooks",
        "D.has cooked",
        "答案：B",
        "20.I didn’t expect you to turn _____ at the meeting yesterday.",
        "A.up",
        "B.to",
        "C.out",
        "D.over",
        "答案：A",
        "16.John succeeded _______ what he wanted.",
        "A.to get     ",
        "B.to getting         ",
        "C.in getting          ",
        "D.and getting       ",
        "答案：C",
        "17.You______to the meeting this afternoon if you have something important to do.",
        "A.needn’t to come",
        "B.don’t need come",
        "C.don’t need coming",
        "D.needn’t come",
        "答案：D",
        "20.His salary as a driver is much higher than ________.",
        "A.a porter",
        "B.is a porter",
        "C.as a porter",
        "D.that of a porter",
        "答案：D",
        "16.This kind of plant ______ a lot of water at all times.",
        "A.assumes           ",
        "B.limits                ",
        "C.produces          ",
        "D.requires",
        "答案：D",
        "17.“Town Hall is the tallest building in the city.” “_______ from here?”",
        "A.Can it see     ",
        "B.Can it be seen         ",
        "C.Can be seeing         ",
        "D.Can see   ",
        "答案：B",
        "19.-  _______ is your girl friend like? - She is very kind and good-looking.",
        "A.How",
        "B.What",
        "C.Which",
        "D.Who",
        "答案：B",
        "20.Jane’s dress is similar in design ______ her sister’s.",
        "A.like",
        "B.with",
        "C.to",
        "D.as",
        "答案：C",
        "16.I took the medicine, but it didn’t _______.",
        "A.work          ",
        "B.help",
        "C.make              ",
        "D.affect ",
        "答案：A",
        "17.Neither Jack nor I ________ able to persuade his father to attend the wedding.",
        "A.am",
        "B.are",
        "C.were",
        "D.is",
        "答案：A",
        "18.I won’t make the _______ mistake next time.",
        "A.like",
        "B.same",
        "C.near",
        "D.similar",
        "答案：B",
        "20.The young lady coming over to us _____ our English teacher; the way she walks tells us that!",
        "A.must be",
        "B.can be",
        "C.would be",
        "D.could be",
        "答案：A",
        "16.Don’t worry. There’s still _____ time to go.",
        "A.little",
        "B.a little",
        "C.few",
        "D.a few",
        "答案：B",
        "17.He likes to swim _______.",
        "A.and to play football       ",
        "B.and playing football          ",
        "C.but play football         ",
        "D.and he also likes playing football     ",
        "答案：A",
        "18.I didn’t know what to do, but then an idea suddenly ________ to me.",
        "A.appeared",
        "B.happened",
        "C.occurred",
        "D.emerged",
        "答案：C",
        "20.He _______ lives in the house where he was born.",
        "A.already",
        "B.yet",
        "C.still",
        "D.ever",
        "答案：C",
        "16.His example _______ that everyone can become a useful person in society so long as he is willing to work hard.",
        "A.expresses          ",
        "B.thinks       ",
        "C.indicates         ",
        "D.supplies         ",
        "答案：C",
        "18.I fell and hurt myself while I ________ basketball yesterday.",
        "A.was playing",
        "B.am playing",
        "C.play",
        "D.played",
        "答案：A",
        "19.He _______ driving me home, even though I told him I lived nearby.",
        "A.insisted on",
        "B.insisted at",
        "C.insisted that",
        "D.insisted in",
        "答案：A",
        "20.Tom is so talkative. I’m sure you’ll soon get tired _______ him.",
        "A.of",
        "B.with",
        "C.at",
        "D.on",
        "答案：A"
    ]
}]