window.english2json = [
[
"—( ) —He teaches physics in a school.",
"A. Who is your father?",
"B. Where is your father?",
"C. What's your father?",
"D. Which is your father?",
"标准答案：C",
],
[
"—( ). I hope I haven’t hurt you. —It’s all right.",
"A. Oh, I’m sorry.",
"B. Oh, I'm regretful.",
"C. Oh, excuse me.",
"D. Oh, help me.",
"标准答案：A",
],
[
"— ( ) —If it weren’t for the climate, I’d like it very much.",
"A. I hope you're enjoying your stay here.",
"B. What is the weather like today?",
"C. What is the weather?",
"D. Are you feeling sick?",
"标准答案：A",
],
[
"—( ). It will help you a lot. —That’s a good idea. Let’s make some.",
"A. I promise to get you some coffee.",
"B. Would you please make me some coffee?",
"C. Help yourself to some coffee.",
"D. You'd better have some coffee.",
"标准答案：D",
],
[
"—( ). —I’ve caught a bad cold and got a sour throat.",
"A. Do you have something to declare, sir?",
"B. Good morning. May I help you?",
"C. How have you got along recently",
"D. What seems to be the problem?",
"标准答案：D",
],
[
"—( ). —Oh, well, I will speak a little slower.",
"A. What do you mean by that?",
"B. Would you please see that again?",
"C. Do you speak English?",
"D. I'm sorry. I can't follow you.",
"标准答案：D",
],
[
"—( ). —Ten yuan a kilo.",
"A. How many do you want?",
"B. What is the weight?",
"C. How much is the meat?",
"D. How much do you know?",
"标准答案：C",
],
[
"—( ). —Yes, I think so.",
"A. Am I supposed to get over and see Caroline?",
"B. I went to see Caroline this morning.",
"C. I hear that Caroline is ill in hospital.",
"D. Why is Caroline staying in hospital?",
"标准答案：A",
],
[
"—A table for two, please. —( ).",
"A. It's a pleasure.",
"B. This way, please.",
"C. What can I do for you?",
"D. Are you ready to order？",
"标准答案：B",
],
[
"—Allow me introduce myself. I’m Li Hua. —( ).",
"A. I’m Todd Smith. It’s nice to meet you.",
"B. I’m Todd Smith. How old are you?",
"C. How are you?",
"D. Oh, here is my card. You can have a look.",
"标准答案：A",
],
[
"—Are there many drugstores around here? —( ).",
"A. Yes, it is.",
"B. Yes, there is one on the left corner.",
"C. No, it isn't.",
"D. Oh, you must have a cold.",
"标准答案：B",
],
[
"—Are you fond of reading novels? —( ).",
"A. I found one novel.",
"B. Novels cannot read.",
"C. Novels are bad.",
"D. Yes, I like reading novels.",
"标准答案：D",
],
[
"—Are you ready to order dessert, please? —( ).",
"A. No, please.",
"B. Please don't order it.",
"C. No, don't mention it.",
"D. Yes, I'd like some chocolate cake.",
"标准答案：D",
],
[
"—Bob, you have a very successful business! ( ). —Thank you!",
"A. You have a good sense of humor.",
"B. Enjoy yourself.",
"C. You two make a lovely couple.",
"D. Well done.",
"标准答案：D",
],
[
"—Can I ask you a few questions? —( ).",
"A. What do you do?",
"B. It's a good idea.",
"C. No, thanks.",
"D. Certainly.",
"标准答案：D",
],
[
"—Can I borrow your camera for a couple of days? —( ).",
"A. Yes, please take it away.",
"B. No, please don't.",
"C. Help yourselves.",
"D. Sure, here you are.",
"标准答案：D",
],
[
"—Can I get you a cup of tea? —( ).",
"A. That's very kind of you.",
"B. With pleasure.",
"C. You can, please.",
"D. Thank you for the tea.",
"标准答案：A",
],
[
"—Can I do anything for you? —( ). I can manage myself.",
"A. Of course you can.",
"B. Please do not.",
"C. Help yourselves.",
"D. No, it's OK.",
"标准答案：D",
],
[
"—Can I look at the menu for a few more minutes before I decide? —Of course. ( ) sir.",
"A. Make yourself at home.",
"B. Enjoy yourself.",
"C. It doesn't matter.",
"D. Take your time.",
"标准答案：D",
],
[
"—Can I speak to Mr. Brown, please? —Yes,( ).",
"A. this is me.",
"B. I am Mr. Brown.",
"C. Brown is speaking.",
"D. please speak.",
"标准答案：C",
],
[
"—Can you go to the concert with us? —( ).",
"A. Sorry, I can't.",
"B. I'd love to.",
"C. Let's go.",
"D. Of course.",
"标准答案：B",
],
[
"—Can you mend the bike? —( ).",
"A. Sorry, I think so.",
"B. Yes, please.",
"C. Thanks.",
"D. Sorry, I don't think so.",
"标准答案：D",
],
[
"—Carol, you look very well. —Thank you, Jane. You look wonderful too. Your weekend tennis must have done you good. —( ).",
"A. That's very kind of you.",
"B. Are you kidding? Thank you anyway.",
"C. You think so? That's encourageing.",
"D. I don't believe it. You are flattering me.",
"标准答案：C",
],
[
"—Congratulations! You won the first prize in the English speech contest. —( ).",
"A. Yes, I beat the others.",
"B. No, no, I didn't do well.",
"C. Thank you.",
"D. It's a pleasure.",
"标准答案：C",
],
[
"—Could you buy some salt on your way home? —( ).",
"A. All right.",
"B. Is that all.",
"C. Just a few.",
"D. Let me see.",
"标准答案：A",
],
[
"—Could you please help me with my homework, please? —( ). I have to go to a meeting right now.",
"A. No, no way.",
"B. No, I couldn't.",
"C. No, I can't.",
"D. Sorry, I can't.",
"标准答案：D",
],
[
"—Could you pass me the salt and pepper? —( ).",
"A. Sorry, I didn't know what you mean.",
"B. Ok, here you are.",
"C. No, I won't.",
"D. I don't know.",
"标准答案：B",
],
[
"—Could you tell me where the nearest parking lot is? —( ).",
"A. Don't ask me.",
"B. Parking is very difficult.",
"C. Sorry, I am a stranger here.",
"D. Sorry, you can't park here.",
"标准答案：C",
],
[
"—David injured his leg playing football yesterday. —Really? ( ).",
"A. How are you?",
"B. Why does he play football?",
"C. How did that happen?",
"D. What a poor man?",
"标准答案：C",
],
[
"—Did you say you liked this novel? —( ). I said it’s not bad.",
"A. Not exactly.",
"B. I don't see why.",
"C. You're great.",
"D. That's quite all right.",
"标准答案：A",
],
[
"—Do we have any assignment for next class? —( ).",
"A. Professors are not here.",
"B. It is great.",
"C. I missed the class too.",
"D. Nobody likes to do it.",
"标准答案：C",
],
[
"—Do you happen to have twenty dollars with you? —( ). —I want to buy a notebook.",
"A. How do you want it?",
"B. How much?",
"C. What for?",
"D. When can you pay me back?",
"标准答案：C",
],
[
"—Do you know the girl over there? —( ).",
"A. How can I know?",
"B. Yes, I remember now.",
"C. It's Linda, my teacher's daughter.",
"D. She is a good girl.",
"标准答案：C",
],
[
"—Do you like to play basketball? —( ).",
"A. Perhaps.",
"B. No, Tom doesn't like it.",
"C. I am crazy about it.",
"D. I am pleased about it.",
"标准答案：C",
],
[
"—Do you mind if I close the window? I feel a bit cold. —( ).",
"A. Of course.",
"B. I'd rather not.",
"C. Go ahead.",
"D. Why not?",
"标准答案：C",
],
[
"—Do you think this is a nice place? —( ).",
"A. That's all right.",
"B. You're well.",
"C. No, it's not here.",
"D. Yes, I think so.",
"标准答案：D",
],
[
"—Does No. 20 bus stop at our school? —( ).",
"A. I go to school by bus.",
"B. I'm afraid not.",
"C. You are welcome.",
"D. I will not take No. 20 bus.",
"标准答案：B",
],
[
"—Don’t forget to phone me when you get home. Just to let me know you’ve arrived safely. ( ). —OK.",
"A. With pleasure.",
"B. Have a nice trip.",
"C. Don't mention it.",
"D. It's very nice of you.",
"标准答案：B",
],
[
"—Excuse me, can I have a seat? —( ).",
"A. Be hurry.",
"B. Come on.",
"C. Yes, please.",
"D. Do you mind?",
"标准答案：C",
],
[
"—Excuse me, I think there seems to be a mistake. —( ).",
"A. Really? I'm sorry.",
"B. I can't believe it.",
"C. I'm sure there is not mistake.",
"D. Impossible.",
"标准答案：A",
],
[
"Jane always enjoys ( ) to popular music at home on Friday evenings.",
"A. listening",
"B. to listen",
"C. listen",
"D. listened",
"标准答案：A",
],
[
"Jane’s dress is similar in design ( ) her sister’s.",
"A. for",
"B. and",
"C. to",
"D. but",
"标准答案：C",
],
[
"Jenny is learning Japanese. ( ) her brother.",
"A. So is",
"B. So does",
"C. So did",
"D. So do",
"标准答案：A",
],
[
"John and Bob have returned but ( ) students in the class haven’t come back yet.",
"A. one",
"B. others",
"C. some",
"D. the other",
"标准答案：D",
],
[
"John didn’t know how to get to the station, so he stopped ( ).",
"A. to ask",
"B. asking",
"C. asked",
"D. be asked",
"标准答案：A",
],
[
"John has never been on time, ( )?",
"A. he has",
"B. he have",
"C. has he",
"D. do we",
"标准答案：C",
],
[
"He succeeded ( ) what he wanted",
"A. to get",
"B. got",
"C. in getting",
"D. gotten",
"标准答案：C",
],
[
"—Can I borrow your CD player? —Sorry,( ) is broken.",
"A. me",
"B. us",
"C. mine",
"D. my",
"标准答案：C",
],
[
"Let us ( ) the picture.",
"A. look",
"B. watch",
"C. listen",
"D. have a look at",
"标准答案：D",
],
[
"Let’s start our meeting immediately ( ) everyone has arrived.",
"A. but",
"B. no",
"C. and",
"D. now that",
"标准答案：D",
],
[
"He wrote a poem when he made a tour to ( ) was once a battle field.",
"A. what",
"B. which",
"C. that",
"D. and",
"标准答案：A",
],
[
"He says he will study physics as his ( ), and he hopes to be a physicist.",
"A. kind",
"B. present",
"C. sister",
"D. major",
"标准答案：D",
],
[
"Listen! Someone ( ) the piano in the next room.",
"A. play",
"B. is playing",
"C. are playing",
"D. to play",
"标准答案：B",
],
[
"Little ( ) about his own safety, though he was in great danger himself.",
"A. he has",
"B. he did care",
"C. did he care",
"D. he cared",
"标准答案：C",
],
[
"Look at ( )! How nice it looks!",
"A. the children",
"B. the apples",
"C. the stars",
"D. the moon",
"标准答案：D",
],
[
"Lucy’s answer is different from ( ). I agree with ( ).",
"A. me, us",
"B. me, our",
"C. yours, her",
"D. you, you",
"标准答案：C",
],
[
"Many people complained that the hospital ( ) patients too much for the medicine and medical treatment.",
"A. charge",
"B. charges",
"C. charged",
"D. being charged",
"标准答案：C",
],
[
"Mark told me that the job would be finished by September, ( ) personally I doubt very much.",
"A. what",
"B. why",
"C. that",
"D. which",
"标准答案：D",
],
[
"Mathematics ( ) study or science of numbers.",
"A. is",
"B. are",
"C. am",
"D. be",
"标准答案：A",
],
[
"Mike is better than Peter ( ) swimming.",
"A. in",
"B. at",
"C. on",
"D. under",
"标准答案：B",
],
[
"He insists ( ) in this hotel.",
"A. on stay",
"B. staying",
"C. that he stay",
"D. stayed",
"标准答案：C",
],
[
"She said she met him ( ) chance yesterday morning.",
"A. with",
"B. by",
"C. to",
"D. on",
"标准答案：B",
],
[
"More than one passenger ( ) in this accident.",
"A. have been injured",
"B. injure",
"C. has been injured",
"D. injured",
"标准答案：A",
],
[
"He isn’t likely ( ) now. It’s too late.",
"A. come",
"B. comes",
"C. to come",
"D. came",
"标准答案：C",
],
[
"Mom, I’m thirsty. Would you please give me some ( )?",
"A. salt",
"B. sand",
"C. food",
"D. water",
"标准答案：D",
],
[
"My cousin is very busy with his work. He has ( ) time to read newspaper.",
"A. little",
"B. few",
"C. a few",
"D. a little",
"标准答案：A",
],
[
"My leg has ( ) completely, so I can take part in the competition.",
"A. heal",
"B. healed",
"C. heals",
"D. healing",
"标准答案：B",
],
[
"My sister has been working in that factory ever ( ) it was set up.",
"A. since",
"B. but",
"C. again",
"D. not",
"标准答案：A",
],
[
"His teaching has profound ( ) on me.",
"A. effect",
"B. matter",
"C. danger",
"D. pink",
"标准答案：A",
],
[
"—My watch is missing. —You ( ) it on the desk in your room.",
"A. have to leave",
"B. should leave",
"C. must have left",
"D. shall leave",
"标准答案：C",
],
[
"Nancy is ( ) girl.",
"A. a eighteen years-old",
"B. a eighteen year old",
"C. an eighteen-year old",
"D. an eighteen-year-old",
"标准答案：D",
],
[
"Nearly everybody ( ) colds in winter.",
"A. suffered with",
"B. suffering",
"C. suffers from",
"D. suffered by",
"标准答案：C",
],
[
"Neither Jack nor I ( ) able to persuade his father to attend the wedding.",
"A. am",
"B. is",
"C. not",
"D. are",
"标准答案：A",
],
[
"Never before ( ) see such a terrible car accident on the road.",
"A. do I",
"B. do he",
"C. do",
"D. did I",
"标准答案：D",
],
[
"No one can ( ) how the election will turn out, as there are many unknown facts.",
"A. remember",
"B. forget",
"C. predict",
"D. get",
"标准答案：C",
],
[
"No one can deny the fact that he was the person ( ) for the death of that lovely boy.",
"A. responsbile",
"B. resistant",
"C. allow",
"D. work",
"标准答案：A",
],
[
"No one was aware ( ) the danger ahead at that time.",
"A. of",
"B. at",
"C. on",
"D. off",
"标准答案：A",
],
[
"No sooner ( ) taken off ( ) the engine went out of order.",
"A. has the plane, when",
"B. had the plane, than",
"C. the plane have, than",
"D. the plane is, than",
"标准答案：B",
],
[
"He is so tired that he falls ( ) within minutes.",
"A. sleep",
"B. asleep",
"C. to sleep",
"D. sleepy",
"标准答案：B",
],
[
"Not only ( ) study well, but also he is always ready to help others.",
"A. do he",
"B. he does",
"C. does he",
"D. did he",
"标准答案：C",
],
[
"( ) of the farmers has a watch.",
"A. Each",
"B. Every",
"C. Some",
"D. All",
"标准答案：A",
],
[
"Nowadays science fiction isn’t as ( ) as cartoons among teenagers.",
"A. more popular",
"B. popularer",
"C. most popular",
"D. popular",
"标准答案：D",
],
[
"Children usually prefer ( ) TV to ( ).",
"A. watch, read",
"B. watching, reading",
"C. watching, read",
"D. to watch, read",
"标准答案：B",
],
[
"Oh, dear! The key ( ) the lock ( ) in the room.",
"A. for, has been left",
"B. to, leaves",
"C. to, has been left",
"D. for, leaves",
"标准答案：C",
],
[
"One must try his best to ( ) to the new environment in his life.",
"A. adapt",
"B. adopt",
"C. apt",
"D. choose",
"标准答案：A",
],
[
"One needs a good sense of ( ) to ride a bike.",
"A. balance",
"B. end",
"C. good",
"D. flat",
"标准答案：A",
],
[
"Over 50,000 people ( ) in the earthquake that occurred in India.",
"A. are killed",
"B. were killed",
"C. killed",
"D. were being killed",
"标准答案：B",
],
[
"People are still talking about the historic event of years ago, ( ) man walked in space for the first time.",
"A. when",
"B. which",
"C. that",
"D. why",
"标准答案：A",
],
[
"Please don’t have your schedule ( ), or there would be a lot of trouble.",
"A. changed",
"B. change",
"C. to change",
"D. changing",
"标准答案：A",
],
[
"Please help me to give ( ) all the test papers during the break.",
"A. up",
"B. in",
"C. back",
"D. out",
"标准答案：D",
],
[
"Be sure to keep everything in ( ) so that you can find it easily in time of need.",
"A. order",
"B. account",
"C. time",
"D. water",
"标准答案：A",
],
[
"Prices ( ) from season to season.",
"A. come",
"B. enlarge",
"C. rise",
"D. vary",
"标准答案：D",
],
[
"Sam enjoys ( ) stamps and now he has 226 of them.",
"A. collecting",
"B. to collecting",
"C. to collect",
"D. collect",
"标准答案：A",
],
[
"He could do nothing but ( ) to his teacher that he was wrong.",
"A. admit",
"B. admitting",
"C. to admit",
"D. admitted",
"标准答案：A",
],
[
"Scholars believe that social development can easily ( ) language changes.",
"A. talk about",
"B. bring about",
"C. care about",
"D. think about",
"标准答案：B",
],
[
"The weather is too dry. The flowers need ( ).",
"A. watered",
"B. watering",
"C. being watered",
"D. to water",
"标准答案：B",
],
[
"She has two best friends and ( ) of them is in China now.",
"A. neither",
"B. either",
"C. both",
"D. nor",
"标准答案：A",
],
[
"She stared at me ( ) her sharp bright eyes.",
"A. with",
"B. by",
"C. in",
"D. on",
"标准答案：A",
],
[
"She told us such a ( ) story that we were ( ) to tears.",
"A. moving, moving",
"B. moving, moved",
"C. moved, moving",
"D. moved, moved",
"标准答案：B",
],
[
"She went to school as usual ( ) she was ill.",
"A. but",
"B. when",
"C. though",
"D. however",
"标准答案：C"]]